/*****************************************************************************
   raptor_types.h
   Generated By:
   Raptor 2022b_1.0.14751 (6897)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr 19 15:40:22 2024
 *****************************************************************************/

#ifndef RAPTOR_TYPES_H
#define RAPTOR_TYPES_H
#include "rtwtypes.h"
#include "Accelerator_test_build_types.h"
#ifndef NULL
#define NULL                           (0)
#endif
#endif
