/*****************************************************************************
   time.h
   Generated By:
   Raptor 2022b_1.0.14751 (6897)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Fri Apr 19 15:40:22 2024
 *****************************************************************************/

#ifndef TIME_H
#define TIME_H

uint32_T ticks(void);
uint32_T ticks_i(void);
uint32_T ticks_us(void);
uint32_T ticks_us_i(void);

#endif
