/*****************************************************************************
   data.h
   Generated By:
   Raptor 2022b_1.0.14751 (6897)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Mon Apr 15 22:06:38 2024
 *****************************************************************************/

#ifndef __DATA_H
#define __DATA_H
#include "faultmanager.h"
#include "core_env.h"
#include "sws_eep.h"
#include "gnu_pragma_conf.h"
#include "memlay_pub.h"
#include "machine.h"
#define uint64                         unsigned long
#include "sbreset.h"
#undef uint64
#include "reset_auto_conf.h"
#include "reset_pub.h"
#include "codegen_hwe_cpu.h"
#include "e_rtatr.h"
#include "cpu_pub.h"
#include "rtwtypes.h"
#include "raptor_types.h"

/*  SS_DOUBLE  =  0,    / real32_T    /
   SS_SINGLE  =  1,    / real32_T    /
   SS_INT8    =  2,    / int8_T      /
   SS_UINT8   =  3,    / uint8_T     /
   SS_INT16   =  4,    / int16_T     /
   SS_UINT16  =  5,    / uint16_T    /
   SS_INT32   =  6,    / int32_T     /
   SS_UINT32  =  7,    / uint32_T    /
   SS_BOOLEAN =  8     / boolean_T  */
/***** RAM Variables *************************************************/
#define RAMVARIABLES

typedef struct {
  uint8_T INIT_RAM_Variables;
  boolean_T FgndTasksStopped;          /* Type : boolean_T, Storage : RAM,  */
  boolean_T KeySw_Bgnd;                /* Type : boolean_T, Storage : RAM,  */
  boolean_T KeepModuleOn;              /* Type : boolean_T, Storage : RAM,  */
  real32_T AbsoluteTime;               /* Type : real32_T, Storage : RAM,  */
  uint16_T POT1_ADC;                   /* Type : uint16_T, Storage : RAM,  */
  real32_T POT1;                       /* Type : real32_T, Storage : RAM,  */
  uint16_T POT2_ADC;                   /* Type : uint16_T, Storage : RAM,  */
  real32_T POT2;                       /* Type : real32_T, Storage : RAM,  */
  real32_T RPM_IN;                     /* Type : real32_T, Storage : RAM,  */
  real32_T MaxTorqueMap_Y_IN_IDX;      /* Type : real32_T, Storage : RAM,  */
  boolean_T POT1HighProbe;             /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT1LowProbe;              /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT2HighProbe;             /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT2LowProbe;              /* Type : boolean_T, Storage : RAM,  */
  uint32_T EcuAddr_RAM;                /* Type : uint32_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint32_T raptorFaultCounts_X[4];     /* Type : uint32_T, Storage : RAM,  */
  uint32_T raptorFaultCounts_Y[4];     /* Type : uint32_T, Storage : RAM,  */
  uint8_T EEPROM_State;                /* Type : uint8_T, Storage : RAM,  */
} RAMVariables_T;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern RAMVariables_T RAMVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void initRAMVariables(RAMVariables_T*);

/***** CONST Variables *************************************************/
#define CONSTVARIABLES

typedef struct {
  real32_T const POT1_ADCHiPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_ADCLoPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_ADCHiPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_ADCLoPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_InputHighThresh; /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_InputLowThresh;  /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_InputHighThresh; /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_InputLowThresh;  /* Type : real32_T, Storage : CONST,  */
  uint8_T const ModelName[22];         /* Type : uint8_T, Storage : CONST,  */
  uint32_T const BuildNumber;          /* Type : uint32_T, Storage : CONST,  */
  uint8_T const MatlabVersion[13];     /* Type : uint8_T, Storage : CONST,  */
  uint8_T const RaptorVersion[20];     /* Type : uint8_T, Storage : CONST,  */
  uint8_T const SwIdTxt[26];           /* Type : uint8_T, Storage : CONST,  */
  uint8_T const CalIdTxt[30];          /* Type : uint8_T, Storage : CONST,  */
  uint8_T const BuildUID[21];          /* Type : uint8_T, Storage : CONST,  */
  uint16_T const IdTableRev;           /* Type : uint16_T, Storage : CONST,  */
  uint32_T const HardwareType;         /* Type : uint32_T, Storage : CONST,  */
  uint8_T const DateStamp[20];         /* Type : uint8_T, Storage : CONST,  */
} CONSTVariables_T;

#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

extern const CONSTVariables_T CONSTVariables;

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

extern void initCONSTVariables(const CONSTVariables_T*);
typedef enum {
  EE_INIT = 0,
  EE_LOADED_DEFAULTS = 1,
  EE_LOADED_DEFAULTS_AFTER_PROGRAMMING = 2,
  EE_LOADED_DEFAULTS_INCORRECT_CRC = 3,
  EE_LOADED_DEFAULTS_INCORRECT_EEID = 4,
  EE_LOADED_DEFAULTS_ERROR_READING = 5,
  EE_LOADED_DEFAULTS_FAILED_DRV_INIT = 6,
  EE_LOADED_SAVED_VALUES_AFTER_PROGRAMMING = 7,
  EE_LOADED_SAVED_VALUES = 8,
  EE_LOADED_BACKUP_VALUES = 9,
  EE_STORE_IN_PROGESS = 10,
  EE_STORE_FAILED = 11,
  EE_STORE_SUCCESS = 12,
} EE_STATES;

/***** EE Variables *************************************************/
#define EEVARIABLES

typedef struct {
  uint32_T WriteCnt;                  /* Write Count: Identifies active Copy 	*/
  uint32_T EE_UniqID;
  uint8_T raptorFaultNonVolatileBits[4];/* Type : uint8_T, Storage : EEPROM */
  real32_T KeySwHiTimeThr;             /* Type : real32_T, Storage : CAL */
  real32_T KeySwLoTimeThr;             /* Type : real32_T, Storage : CAL */
  real32_T RPM[33];                    /* Type : real32_T, Storage : CAL */
  real32_T MaxTorqueMap[33];           /* Type : real32_T, Storage : CAL */
  uint32_T POT1_InputHi_X_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputHi_Y_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputLow_X_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputLow_Y_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputHi_X_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputHi_Y_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputLow_X_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputLow_Y_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_BC_ID;            /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_RX_ID;            /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_TX_ID;            /* Type : uint32_T, Storage : CAL */
  uint8_T INPUT29_ADCMon_HoldCount;    /* Type : uint8_T, Storage : CAL */
  uint16_T CAN1__XCP_Security;         /* Type : uint16_T, Storage : CAL */
  uint16_T CAN1_Startup_Delay;         /* Type : uint16_T, Storage : CAL */
  uint8_T CAN1_ErrorCheck_Interval;    /* Type : uint8_T, Storage : CAL */
  uint8_T CAN1_ErrorPassive_Delay;     /* Type : uint8_T, Storage : CAL */
  uint16_T CAN2_Startup_Delay;         /* Type : uint16_T, Storage : CAL */
  uint8_T CAN2_ErrorCheck_Interval;    /* Type : uint8_T, Storage : CAL */
  uint8_T CAN2_ErrorPassive_Delay;     /* Type : uint8_T, Storage : CAL */
  E_FaultOperation raptorFaultOperation[4];
                                    /* Type : E_FaultOperation, Storage : CAL */
  uint8_T InjCDrv_EndOfStart;          /* Type : uint8_T, Storage : CAL */
  uint8_T EndOfStart;                  /* Type : uint8_T, Storage : CAL */
  uint16_T CRC;
         /* CRC - Last two bytes per SDK spec for CRC Calc (Parker Specific) 	*/
} EEVariables_T;

extern const EEVariables_T EEVariables_DEFAULT;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern EEVariables_T EEVariables_RAMShadow;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void App_EE_WriteAsync(uint8_T);
extern uint16_T Reset_xHistBuf[8] __attribute__ ((asection(".bss.earlycleared",
  "f=aw")));
extern struct Reset_Environment Reset_Env;
extern void App_EE_Store(void);
extern void App_EE_Defaults(void);
typedef struct {
  uint8_T INIT_RAM_EditVariables;
  uint16_T POT1_ADC_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT1_ADC_OvrSts;/* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T POT1_OvrVal;/* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T POT1_OvrSts;    /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T POT2_ADC_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT2_ADC_OvrSts;/* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T POT2_OvrVal;/* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T POT2_OvrSts;    /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
} RAMEditVariables_T;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern RAMEditVariables_T RAMEditVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void initRAMEditVariables(void);

/***** #DEFINES Accessors *************************************************/
#define FgndTasksStopped_Data()        (RAMVariables.FgndTasksStopped)
#define FgndTasksStopped_Ptr()         (&(RAMVariables.FgndTasksStopped))
#define FgndTasksStopped_ELEMENTS()    (1 * 1)
#define KeySwHiTimeThr_Data()          (EEVariables_RAMShadow.KeySwHiTimeThr)
#define KeySwHiTimeThr_Ptr()           (&(EEVariables_RAMShadow.KeySwHiTimeThr))
#define KeySwHiTimeThr_ELEMENTS()      (1 * 1)
#define KeySwLoTimeThr_Data()          (EEVariables_RAMShadow.KeySwLoTimeThr)
#define KeySwLoTimeThr_Ptr()           (&(EEVariables_RAMShadow.KeySwLoTimeThr))
#define KeySwLoTimeThr_ELEMENTS()      (1 * 1)
#define KeySw_Bgnd_Data()              (RAMVariables.KeySw_Bgnd)
#define KeySw_Bgnd_Ptr()               (&(RAMVariables.KeySw_Bgnd))
#define KeySw_Bgnd_ELEMENTS()          (1 * 1)
#define KeepModuleOn_Data()            (RAMVariables.KeepModuleOn)
#define KeepModuleOn_Ptr()             (&(RAMVariables.KeepModuleOn))
#define KeepModuleOn_ELEMENTS()        (1 * 1)
#define AbsoluteTime_Data()            (RAMVariables.AbsoluteTime)
#define AbsoluteTime_Ptr()             (&(RAMVariables.AbsoluteTime))
#define AbsoluteTime_ELEMENTS()        (1 * 1)
#define POT1_ADC_OvrVal_Data()         (RAMEditVariables.POT1_ADC_OvrVal)
#define POT1_ADC_OvrVal_Ptr()          (&(RAMEditVariables.POT1_ADC_OvrVal))
#define POT1_ADC_OvrVal_ELEMENTS()     (1 * 1)
#define POT1_ADC_Data()                (RAMVariables.POT1_ADC)
#define POT1_ADC_Ptr()                 (&(RAMVariables.POT1_ADC))
#define POT1_ADC_ELEMENTS()            (1 * 1)
#define POT1_ADC_OvrSts_Data()         (RAMEditVariables.POT1_ADC_OvrSts)
#define POT1_ADC_OvrSts_Ptr()          (&(RAMEditVariables.POT1_ADC_OvrSts))
#define POT1_ADC_OvrSts_ELEMENTS()     (1 * 1)
#define POT1_ADCHiPT_Data()            (CONSTVariables.POT1_ADCHiPT)
#define POT1_ADCHiPT_Ptr()             (&(CONSTVariables.POT1_ADCHiPT))
#define POT1_ADCHiPT_ELEMENTS()        (1 * 1)
#define POT1_ADCLoPT_Data()            (CONSTVariables.POT1_ADCLoPT)
#define POT1_ADCLoPT_Ptr()             (&(CONSTVariables.POT1_ADCLoPT))
#define POT1_ADCLoPT_ELEMENTS()        (1 * 1)
#define POT1_OvrVal_Data()             (RAMEditVariables.POT1_OvrVal)
#define POT1_OvrVal_Ptr()              (&(RAMEditVariables.POT1_OvrVal))
#define POT1_OvrVal_ELEMENTS()         (1 * 1)
#define POT1_Data()                    (RAMVariables.POT1)
#define POT1_Ptr()                     (&(RAMVariables.POT1))
#define POT1_ELEMENTS()                (1 * 1)
#define POT1_OvrSts_Data()             (RAMEditVariables.POT1_OvrSts)
#define POT1_OvrSts_Ptr()              (&(RAMEditVariables.POT1_OvrSts))
#define POT1_OvrSts_ELEMENTS()         (1 * 1)
#define POT2_ADC_OvrVal_Data()         (RAMEditVariables.POT2_ADC_OvrVal)
#define POT2_ADC_OvrVal_Ptr()          (&(RAMEditVariables.POT2_ADC_OvrVal))
#define POT2_ADC_OvrVal_ELEMENTS()     (1 * 1)
#define POT2_ADC_Data()                (RAMVariables.POT2_ADC)
#define POT2_ADC_Ptr()                 (&(RAMVariables.POT2_ADC))
#define POT2_ADC_ELEMENTS()            (1 * 1)
#define POT2_ADC_OvrSts_Data()         (RAMEditVariables.POT2_ADC_OvrSts)
#define POT2_ADC_OvrSts_Ptr()          (&(RAMEditVariables.POT2_ADC_OvrSts))
#define POT2_ADC_OvrSts_ELEMENTS()     (1 * 1)
#define POT2_ADCHiPT_Data()            (CONSTVariables.POT2_ADCHiPT)
#define POT2_ADCHiPT_Ptr()             (&(CONSTVariables.POT2_ADCHiPT))
#define POT2_ADCHiPT_ELEMENTS()        (1 * 1)
#define POT2_ADCLoPT_Data()            (CONSTVariables.POT2_ADCLoPT)
#define POT2_ADCLoPT_Ptr()             (&(CONSTVariables.POT2_ADCLoPT))
#define POT2_ADCLoPT_ELEMENTS()        (1 * 1)
#define POT2_OvrVal_Data()             (RAMEditVariables.POT2_OvrVal)
#define POT2_OvrVal_Ptr()              (&(RAMEditVariables.POT2_OvrVal))
#define POT2_OvrVal_ELEMENTS()         (1 * 1)
#define POT2_Data()                    (RAMVariables.POT2)
#define POT2_Ptr()                     (&(RAMVariables.POT2))
#define POT2_ELEMENTS()                (1 * 1)
#define POT2_OvrSts_Data()             (RAMEditVariables.POT2_OvrSts)
#define POT2_OvrSts_Ptr()              (&(RAMEditVariables.POT2_OvrSts))
#define POT2_OvrSts_ELEMENTS()         (1 * 1)
#define RPM_IN_Data()                  (RAMVariables.RPM_IN)
#define RPM_IN_Ptr()                   (&(RAMVariables.RPM_IN))
#define RPM_IN_ELEMENTS()              (1 * 1)
#define RPM_Data()                     (EEVariables_RAMShadow.RPM)
#define RPM_Ptr()                      (&(EEVariables_RAMShadow.RPM))
#define RPM_ELEMENTS()                 (1 * 33)
#define MaxTorqueMap_Data()            (EEVariables_RAMShadow.MaxTorqueMap)
#define MaxTorqueMap_Ptr()             (&(EEVariables_RAMShadow.MaxTorqueMap))
#define MaxTorqueMap_ELEMENTS()        (1 * 33)
#define MaxTorqueMap_Y_IN_IDX_Data()   (RAMVariables.MaxTorqueMap_Y_IN_IDX)
#define MaxTorqueMap_Y_IN_IDX_Ptr()    (&(RAMVariables.MaxTorqueMap_Y_IN_IDX))
#define MaxTorqueMap_Y_IN_IDX_ELEMENTS() (1 * 1)
#define POT1_InputHighThresh_Data()    (CONSTVariables.POT1_InputHighThresh)
#define POT1_InputHighThresh_Ptr()     (&(CONSTVariables.POT1_InputHighThresh))
#define POT1_InputHighThresh_ELEMENTS() (1 * 1)
#define POT1_InputHi_X_Limit_Data()    (EEVariables_RAMShadow.POT1_InputHi_X_Limit)
#define POT1_InputHi_X_Limit_Ptr()     (&(EEVariables_RAMShadow.POT1_InputHi_X_Limit))
#define POT1_InputHi_X_Limit_ELEMENTS() (1 * 1)
#define POT1_InputHi_Y_Limit_Data()    (EEVariables_RAMShadow.POT1_InputHi_Y_Limit)
#define POT1_InputHi_Y_Limit_Ptr()     (&(EEVariables_RAMShadow.POT1_InputHi_Y_Limit))
#define POT1_InputHi_Y_Limit_ELEMENTS() (1 * 1)
#define POT1_InputLowThresh_Data()     (CONSTVariables.POT1_InputLowThresh)
#define POT1_InputLowThresh_Ptr()      (&(CONSTVariables.POT1_InputLowThresh))
#define POT1_InputLowThresh_ELEMENTS() (1 * 1)
#define POT1_InputLow_X_Limit_Data()   (EEVariables_RAMShadow.POT1_InputLow_X_Limit)
#define POT1_InputLow_X_Limit_Ptr()    (&(EEVariables_RAMShadow.POT1_InputLow_X_Limit))
#define POT1_InputLow_X_Limit_ELEMENTS() (1 * 1)
#define POT1_InputLow_Y_Limit_Data()   (EEVariables_RAMShadow.POT1_InputLow_Y_Limit)
#define POT1_InputLow_Y_Limit_Ptr()    (&(EEVariables_RAMShadow.POT1_InputLow_Y_Limit))
#define POT1_InputLow_Y_Limit_ELEMENTS() (1 * 1)
#define POT1HighProbe_Data()           (RAMVariables.POT1HighProbe)
#define POT1HighProbe_Ptr()            (&(RAMVariables.POT1HighProbe))
#define POT1HighProbe_ELEMENTS()       (1 * 1)
#define POT1LowProbe_Data()            (RAMVariables.POT1LowProbe)
#define POT1LowProbe_Ptr()             (&(RAMVariables.POT1LowProbe))
#define POT1LowProbe_ELEMENTS()        (1 * 1)
#define POT2_InputHighThresh_Data()    (CONSTVariables.POT2_InputHighThresh)
#define POT2_InputHighThresh_Ptr()     (&(CONSTVariables.POT2_InputHighThresh))
#define POT2_InputHighThresh_ELEMENTS() (1 * 1)
#define POT2_InputHi_X_Limit_Data()    (EEVariables_RAMShadow.POT2_InputHi_X_Limit)
#define POT2_InputHi_X_Limit_Ptr()     (&(EEVariables_RAMShadow.POT2_InputHi_X_Limit))
#define POT2_InputHi_X_Limit_ELEMENTS() (1 * 1)
#define POT2_InputHi_Y_Limit_Data()    (EEVariables_RAMShadow.POT2_InputHi_Y_Limit)
#define POT2_InputHi_Y_Limit_Ptr()     (&(EEVariables_RAMShadow.POT2_InputHi_Y_Limit))
#define POT2_InputHi_Y_Limit_ELEMENTS() (1 * 1)
#define POT2_InputLowThresh_Data()     (CONSTVariables.POT2_InputLowThresh)
#define POT2_InputLowThresh_Ptr()      (&(CONSTVariables.POT2_InputLowThresh))
#define POT2_InputLowThresh_ELEMENTS() (1 * 1)
#define POT2_InputLow_X_Limit_Data()   (EEVariables_RAMShadow.POT2_InputLow_X_Limit)
#define POT2_InputLow_X_Limit_Ptr()    (&(EEVariables_RAMShadow.POT2_InputLow_X_Limit))
#define POT2_InputLow_X_Limit_ELEMENTS() (1 * 1)
#define POT2_InputLow_Y_Limit_Data()   (EEVariables_RAMShadow.POT2_InputLow_Y_Limit)
#define POT2_InputLow_Y_Limit_Ptr()    (&(EEVariables_RAMShadow.POT2_InputLow_Y_Limit))
#define POT2_InputLow_Y_Limit_ELEMENTS() (1 * 1)
#define POT2HighProbe_Data()           (RAMVariables.POT2HighProbe)
#define POT2HighProbe_Ptr()            (&(RAMVariables.POT2HighProbe))
#define POT2HighProbe_ELEMENTS()       (1 * 1)
#define POT2LowProbe_Data()            (RAMVariables.POT2LowProbe)
#define POT2LowProbe_Ptr()             (&(RAMVariables.POT2LowProbe))
#define POT2LowProbe_ELEMENTS()        (1 * 1)
#define CAN1__XCP_BC_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_BC_ID)
#define CAN1__XCP_BC_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_BC_ID))
#define CAN1__XCP_BC_ID_ELEMENTS()     (1 * 1)
#define CAN1__XCP_RX_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_RX_ID)
#define CAN1__XCP_RX_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_RX_ID))
#define CAN1__XCP_RX_ID_ELEMENTS()     (1 * 1)
#define CAN1__XCP_TX_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_TX_ID)
#define CAN1__XCP_TX_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_TX_ID))
#define CAN1__XCP_TX_ID_ELEMENTS()     (1 * 1)
#define ModelName_Data()               (CONSTVariables.ModelName)
#define ModelName_Ptr()                (&(CONSTVariables.ModelName))
#define ModelName_ELEMENTS()           (1 * 22)
#define BuildNumber_Data()             (CONSTVariables.BuildNumber)
#define BuildNumber_Ptr()              (&(CONSTVariables.BuildNumber))
#define BuildNumber_ELEMENTS()         (1 * 1)
#define MatlabVersion_Data()           (CONSTVariables.MatlabVersion)
#define MatlabVersion_Ptr()            (&(CONSTVariables.MatlabVersion))
#define MatlabVersion_ELEMENTS()       (1 * 13)
#define RaptorVersion_Data()           (CONSTVariables.RaptorVersion)
#define RaptorVersion_Ptr()            (&(CONSTVariables.RaptorVersion))
#define RaptorVersion_ELEMENTS()       (1 * 20)
#define SwIdTxt_Data()                 (CONSTVariables.SwIdTxt)
#define SwIdTxt_Ptr()                  (&(CONSTVariables.SwIdTxt))
#define SwIdTxt_ELEMENTS()             (1 * 26)
#define CalIdTxt_Data()                (CONSTVariables.CalIdTxt)
#define CalIdTxt_Ptr()                 (&(CONSTVariables.CalIdTxt))
#define CalIdTxt_ELEMENTS()            (1 * 30)
#define BuildUID_Data()                (CONSTVariables.BuildUID)
#define BuildUID_Ptr()                 (&(CONSTVariables.BuildUID))
#define BuildUID_ELEMENTS()            (1 * 21)
#define IdTableRev_Data()              (CONSTVariables.IdTableRev)
#define IdTableRev_Ptr()               (&(CONSTVariables.IdTableRev))
#define IdTableRev_ELEMENTS()          (1 * 1)
#define HardwareType_Data()            (CONSTVariables.HardwareType)
#define HardwareType_Ptr()             (&(CONSTVariables.HardwareType))
#define HardwareType_ELEMENTS()        (1 * 1)
#define EcuAddr_RAM_Data()             (RAMVariables.EcuAddr_RAM)
#define EcuAddr_RAM_Ptr()              (&(RAMVariables.EcuAddr_RAM))
#define EcuAddr_RAM_ELEMENTS()         (1 * 1)
#define DateStamp_Data()               (CONSTVariables.DateStamp)
#define DateStamp_Ptr()                (&(CONSTVariables.DateStamp))
#define DateStamp_ELEMENTS()           (1 * 20)
#define INPUT29_ADCMon_HoldCount_Data() (EEVariables_RAMShadow.INPUT29_ADCMon_HoldCount)
#define INPUT29_ADCMon_HoldCount_Ptr() (&(EEVariables_RAMShadow.INPUT29_ADCMon_HoldCount))
#define INPUT29_ADCMon_HoldCount_ELEMENTS() (1 * 1)
#define CAN1__XCP_Security_Data()      (EEVariables_RAMShadow.CAN1__XCP_Security)
#define CAN1__XCP_Security_Ptr()       (&(EEVariables_RAMShadow.CAN1__XCP_Security))
#define CAN1__XCP_Security_ELEMENTS()  (1 * 1)
#define CAN1_CANTX_QueueOverrun_Data() (RAMVariables.CAN1_CANTX_QueueOverrun)
#define CAN1_CANTX_QueueOverrun_Ptr()  (&(RAMVariables.CAN1_CANTX_QueueOverrun))
#define CAN1_CANTX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN1_CANTX_QueueCount_Data()   (RAMVariables.CAN1_CANTX_QueueCount)
#define CAN1_CANTX_QueueCount_Ptr()    (&(RAMVariables.CAN1_CANTX_QueueCount))
#define CAN1_CANTX_QueueCount_ELEMENTS() (1 * 1)
#define CAN1_CANTX_QueueMax_Data()     (RAMVariables.CAN1_CANTX_QueueMax)
#define CAN1_CANTX_QueueMax_Ptr()      (&(RAMVariables.CAN1_CANTX_QueueMax))
#define CAN1_CANTX_QueueMax_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueOverrun_Data() (RAMVariables.CAN1_CANRX_QueueOverrun)
#define CAN1_CANRX_QueueOverrun_Ptr()  (&(RAMVariables.CAN1_CANRX_QueueOverrun))
#define CAN1_CANRX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueCount_Data()   (RAMVariables.CAN1_CANRX_QueueCount)
#define CAN1_CANRX_QueueCount_Ptr()    (&(RAMVariables.CAN1_CANRX_QueueCount))
#define CAN1_CANRX_QueueCount_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueMax_Data()     (RAMVariables.CAN1_CANRX_QueueMax)
#define CAN1_CANRX_QueueMax_Ptr()      (&(RAMVariables.CAN1_CANRX_QueueMax))
#define CAN1_CANRX_QueueMax_ELEMENTS() (1 * 1)
#define CAN1_Startup_Delay_Data()      (EEVariables_RAMShadow.CAN1_Startup_Delay)
#define CAN1_Startup_Delay_Ptr()       (&(EEVariables_RAMShadow.CAN1_Startup_Delay))
#define CAN1_Startup_Delay_ELEMENTS()  (1 * 1)
#define CAN1_ErrorCheck_Interval_Data() (EEVariables_RAMShadow.CAN1_ErrorCheck_Interval)
#define CAN1_ErrorCheck_Interval_Ptr() (&(EEVariables_RAMShadow.CAN1_ErrorCheck_Interval))
#define CAN1_ErrorCheck_Interval_ELEMENTS() (1 * 1)
#define CAN1_ErrorPassive_Delay_Data() (EEVariables_RAMShadow.CAN1_ErrorPassive_Delay)
#define CAN1_ErrorPassive_Delay_Ptr()  (&(EEVariables_RAMShadow.CAN1_ErrorPassive_Delay))
#define CAN1_ErrorPassive_Delay_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueOverrun_Data() (RAMVariables.CAN2_CANTX_QueueOverrun)
#define CAN2_CANTX_QueueOverrun_Ptr()  (&(RAMVariables.CAN2_CANTX_QueueOverrun))
#define CAN2_CANTX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueCount_Data()   (RAMVariables.CAN2_CANTX_QueueCount)
#define CAN2_CANTX_QueueCount_Ptr()    (&(RAMVariables.CAN2_CANTX_QueueCount))
#define CAN2_CANTX_QueueCount_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueMax_Data()     (RAMVariables.CAN2_CANTX_QueueMax)
#define CAN2_CANTX_QueueMax_Ptr()      (&(RAMVariables.CAN2_CANTX_QueueMax))
#define CAN2_CANTX_QueueMax_ELEMENTS() (1 * 1)
#define CAN2_Startup_Delay_Data()      (EEVariables_RAMShadow.CAN2_Startup_Delay)
#define CAN2_Startup_Delay_Ptr()       (&(EEVariables_RAMShadow.CAN2_Startup_Delay))
#define CAN2_Startup_Delay_ELEMENTS()  (1 * 1)
#define CAN2_ErrorCheck_Interval_Data() (EEVariables_RAMShadow.CAN2_ErrorCheck_Interval)
#define CAN2_ErrorCheck_Interval_Ptr() (&(EEVariables_RAMShadow.CAN2_ErrorCheck_Interval))
#define CAN2_ErrorCheck_Interval_ELEMENTS() (1 * 1)
#define CAN2_ErrorPassive_Delay_Data() (EEVariables_RAMShadow.CAN2_ErrorPassive_Delay)
#define CAN2_ErrorPassive_Delay_Ptr()  (&(EEVariables_RAMShadow.CAN2_ErrorPassive_Delay))
#define CAN2_ErrorPassive_Delay_ELEMENTS() (1 * 1)
#define raptorFaultNonVolatileBits_Data() (EEVariables_RAMShadow.raptorFaultNonVolatileBits)
#define raptorFaultNonVolatileBits_Ptr() (&(EEVariables_RAMShadow.raptorFaultNonVolatileBits))
#define raptorFaultNonVolatileBits_ELEMENTS() (1 * 4)
#define raptorFaultCounts_X_Data()     (RAMVariables.raptorFaultCounts_X)
#define raptorFaultCounts_X_Ptr()      (&(RAMVariables.raptorFaultCounts_X))
#define raptorFaultCounts_X_ELEMENTS() (1 * 4)
#define raptorFaultCounts_Y_Data()     (RAMVariables.raptorFaultCounts_Y)
#define raptorFaultCounts_Y_Ptr()      (&(RAMVariables.raptorFaultCounts_Y))
#define raptorFaultCounts_Y_ELEMENTS() (1 * 4)
#define raptorFaultOperation_Data()    (EEVariables_RAMShadow.raptorFaultOperation)
#define raptorFaultOperation_Ptr()     (&(EEVariables_RAMShadow.raptorFaultOperation))
#define raptorFaultOperation_ELEMENTS() (1 * 4)
#define InjCDrv_EndOfStart_Data()      (EEVariables_RAMShadow.InjCDrv_EndOfStart)
#define InjCDrv_EndOfStart_Ptr()       (&(EEVariables_RAMShadow.InjCDrv_EndOfStart))
#define InjCDrv_EndOfStart_ELEMENTS()  (1 * 1)
#define EndOfStart_Data()              (EEVariables_RAMShadow.EndOfStart)
#define EndOfStart_Ptr()               (&(EEVariables_RAMShadow.EndOfStart))
#define EndOfStart_ELEMENTS()          (1 * 1)
#define EEPROM_State_Data()            (RAMVariables.EEPROM_State)
#define EEPROM_State_Ptr()             (&(RAMVariables.EEPROM_State))
#define EEPROM_State_ELEMENTS()        (1 * 1)
#define NonVolatileCRC_Data()          (EEVariables_RAMShadow.CRC)
#define NonVolatileCRC_Ptr()           (&(EEVariables_RAMShadow.CRC))

/***** CAL Locator ********************************************************/
#define CALLOC_START                   ((void*)KeySwHiTimeThr_Ptr())
#define CALLOC_LENGTH                  ( sizeof(KeySwHiTimeThr_Data()) + sizeof(KeySwLoTimeThr_Data()) + sizeof(RPM_Data()) + sizeof(MaxTorqueMap_Data()) + sizeof(POT1_InputHi_X_Limit_Data()) + sizeof(POT1_InputHi_Y_Limit_Data()) + sizeof(POT1_InputLow_X_Limit_Data()) + sizeof(POT1_InputLow_Y_Limit_Data()) + sizeof(POT2_InputHi_X_Limit_Data()) + sizeof(POT2_InputHi_Y_Limit_Data()) + sizeof(POT2_InputLow_X_Limit_Data()) + sizeof(POT2_InputLow_Y_Limit_Data()) + sizeof(CAN1__XCP_BC_ID_Data()) + sizeof(CAN1__XCP_RX_ID_Data()) + sizeof(CAN1__XCP_TX_ID_Data()) + sizeof(INPUT29_ADCMon_HoldCount_Data()) + sizeof(CAN1__XCP_Security_Data()) + sizeof(CAN1_Startup_Delay_Data()) + sizeof(CAN1_ErrorCheck_Interval_Data()) + sizeof(CAN1_ErrorPassive_Delay_Data()) + sizeof(CAN2_Startup_Delay_Data()) + sizeof(CAN2_ErrorCheck_Interval_Data()) + sizeof(CAN2_ErrorPassive_Delay_Data()) + sizeof(raptorFaultOperation_Data()) + sizeof(InjCDrv_EndOfStart_Data()) + sizeof(EndOfStart_Data()) + 0)
#endif
