/*****************************************************************************
   data.h
   Generated By:
   Raptor 2022b_1.0.14751 (6897)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu May  9 15:17:16 2024
 *****************************************************************************/

#ifndef __DATA_H
#define __DATA_H
#include "faultmanager.h"
#include "core_env.h"
#include "sws_eep.h"
#include "gnu_pragma_conf.h"
#include "memlay_pub.h"
#include "machine.h"
#define uint64                         unsigned long
#include "sbreset.h"
#undef uint64
#include "reset_auto_conf.h"
#include "reset_pub.h"
#include "codegen_hwe_cpu.h"
#include "e_rtatr.h"
#include "cpu_pub.h"
#include "rtwtypes.h"
#include "raptor_types.h"

/*  SS_DOUBLE  =  0,    / real32_T    /
   SS_SINGLE  =  1,    / real32_T    /
   SS_INT8    =  2,    / int8_T      /
   SS_UINT8   =  3,    / uint8_T     /
   SS_INT16   =  4,    / int16_T     /
   SS_UINT16  =  5,    / uint16_T    /
   SS_INT32   =  6,    / int32_T     /
   SS_UINT32  =  7,    / uint32_T    /
   SS_BOOLEAN =  8     / boolean_T  */
/***** RAM Variables *************************************************/
#define RAMVARIABLES

typedef struct {
  uint8_T INIT_RAM_Variables;
  boolean_T FgndTasksStopped;          /* Type : boolean_T, Storage : RAM,  */
  boolean_T KeySw_Bgnd;                /* Type : boolean_T, Storage : RAM,  */
  boolean_T KeepModuleOn;              /* Type : boolean_T, Storage : RAM,  */
  real32_T AbsoluteTime;               /* Type : real32_T, Storage : RAM,  */
  boolean_T POT1_InputHi_Override;     /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT1_InputLow_Override;    /* Type : boolean_T, Storage : RAM,  */
  uint16_T POT1_ADC;                   /* Type : uint16_T, Storage : RAM,  */
  real32_T POT1;                       /* Type : real32_T, Storage : RAM,  */
  boolean_T POT2_InputHi_Override;     /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT2_InputLow_Override;    /* Type : boolean_T, Storage : RAM,  */
  uint16_T POT2_ADC;                   /* Type : uint16_T, Storage : RAM,  */
  real32_T POT2;                       /* Type : real32_T, Storage : RAM,  */
  real32_T RPM_IN;                     /* Type : real32_T, Storage : RAM,  */
  real32_T MaxTorqueMap_Y_IN_IDX;      /* Type : real32_T, Storage : RAM,  */
  real32_T Torque_cmd;                 /* Type : real32_T, Storage : RAM,  */
  real32_T Direction_cmd;              /* Type : real32_T, Storage : RAM,  */
  boolean_T Precharge_status;          /* Type : boolean_T, Storage : RAM,  */
  boolean_T Starter_button;            /* Type : boolean_T, Storage : RAM,  */
  boolean_T Safety_loop_error_logic;   /* Type : boolean_T, Storage : RAM,  */
  boolean_T RTDS;                      /* Type : boolean_T, Storage : RAM,  */
  uint16_T Temp_adc_raw;               /* Type : uint16_T, Storage : RAM,  */
  real32_T Temp_resistance;            /* Type : real32_T, Storage : RAM,  */
  boolean_T Cooling_fault_any;         /* Type : boolean_T, Storage : RAM,  */
  boolean_T Charge_mode;               /* Type : boolean_T, Storage : RAM,  */
  boolean_T Starter_button_latch_q_naught;/* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_tempSenseOC;         /* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_tempSenseSC;         /* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_tempSenseHigh;       /* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_eradic_temp;         /* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_lowFlowRate;         /* Type : boolean_T, Storage : RAM,  */
  boolean_T fault_eradicFlowRate;      /* Type : boolean_T, Storage : RAM,  */
  real32_T Temp_actual_celsius;        /* Type : real32_T, Storage : RAM,  */
  uint16_T Fan_PWM_D;                  /* Type : uint16_T, Storage : RAM,  */
  boolean_T TSMS_logic_probe;          /* Type : boolean_T, Storage : RAM,  */
  boolean_T IMD_OkHs_probe;            /* Type : boolean_T, Storage : RAM,  */
  boolean_T IMD_GLV_probe;             /* Type : boolean_T, Storage : RAM,  */
  real32_T RPM_val;                    /* Type : real32_T, Storage : RAM,  */
  real32_T TP_val;                     /* Type : real32_T, Storage : RAM,  */
  real32_T APP1;                       /* Type : real32_T, Storage : RAM,  */
  real32_T APP2;                       /* Type : real32_T, Storage : RAM,  */
  boolean_T Throttle_plausibility_probe;/* Type : boolean_T, Storage : RAM,  */
  boolean_T Drive_enable;              /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT1HighProbe;             /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT1LowProbe;              /* Type : boolean_T, Storage : RAM,  */
  uint16_T POT1_ADC_Raw;               /* Type : uint16_T, Storage : RAM,  */
  boolean_T POT2HighProbe;             /* Type : boolean_T, Storage : RAM,  */
  boolean_T POT2LowProbe;              /* Type : boolean_T, Storage : RAM,  */
  uint16_T POT2_ADC_Raw;               /* Type : uint16_T, Storage : RAM,  */
  real32_T Counter;                    /* Type : real32_T, Storage : RAM,  */
  uint16_T GLV_hall_adc;               /* Type : uint16_T, Storage : RAM,  */
  real32_T GLV_hall_amp;               /* Type : real32_T, Storage : RAM,  */
  uint32_T Flow_rate_freq_corrected;   /* Type : uint32_T, Storage : RAM,  */
  uint32_T Flow_rate_gpm;              /* Type : uint32_T, Storage : RAM,  */
  uint16_T BMS_SOC_percent;            /* Type : uint16_T, Storage : RAM,  */
  uint32_T EcuAddr_RAM;                /* Type : uint32_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANTX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN1_CANRX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueOverrun;     /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueCount;       /* Type : uint8_T, Storage : RAM,  */
  uint8_T CAN2_CANTX_QueueMax;         /* Type : uint8_T, Storage : RAM,  */
  uint32_T raptorFaultCounts_X[11];    /* Type : uint32_T, Storage : RAM,  */
  uint32_T raptorFaultCounts_Y[11];    /* Type : uint32_T, Storage : RAM,  */
  uint8_T EEPROM_State;                /* Type : uint8_T, Storage : RAM,  */
} RAMVariables_T;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern RAMVariables_T RAMVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void initRAMVariables(RAMVariables_T*);

/***** CONST Variables *************************************************/
#define CONSTVARIABLES

typedef struct {
  real32_T const POT1_ADCHiPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_ADCLoPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_ADCHiPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_ADCLoPT;         /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_InputHighThresh; /* Type : real32_T, Storage : CONST,  */
  real32_T const POT1_InputLowThresh;  /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_InputHighThresh; /* Type : real32_T, Storage : CONST,  */
  real32_T const POT2_InputLowThresh;  /* Type : real32_T, Storage : CONST,  */
  uint8_T const ModelName[11];         /* Type : uint8_T, Storage : CONST,  */
  uint32_T const BuildNumber;          /* Type : uint32_T, Storage : CONST,  */
  uint8_T const MatlabVersion[13];     /* Type : uint8_T, Storage : CONST,  */
  uint8_T const RaptorVersion[20];     /* Type : uint8_T, Storage : CONST,  */
  uint8_T const SwIdTxt[15];           /* Type : uint8_T, Storage : CONST,  */
  uint8_T const CalIdTxt[19];          /* Type : uint8_T, Storage : CONST,  */
  uint8_T const BuildUID[21];          /* Type : uint8_T, Storage : CONST,  */
  uint16_T const IdTableRev;           /* Type : uint16_T, Storage : CONST,  */
  uint32_T const HardwareType;         /* Type : uint32_T, Storage : CONST,  */
  uint8_T const DateStamp[20];         /* Type : uint8_T, Storage : CONST,  */
} CONSTVariables_T;

#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

extern const CONSTVariables_T CONSTVariables;

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

extern void initCONSTVariables(const CONSTVariables_T*);
typedef enum {
  EE_INIT = 0,
  EE_LOADED_DEFAULTS = 1,
  EE_LOADED_DEFAULTS_AFTER_PROGRAMMING = 2,
  EE_LOADED_DEFAULTS_INCORRECT_CRC = 3,
  EE_LOADED_DEFAULTS_INCORRECT_EEID = 4,
  EE_LOADED_DEFAULTS_ERROR_READING = 5,
  EE_LOADED_DEFAULTS_FAILED_DRV_INIT = 6,
  EE_LOADED_SAVED_VALUES_AFTER_PROGRAMMING = 7,
  EE_LOADED_SAVED_VALUES = 8,
  EE_LOADED_BACKUP_VALUES = 9,
  EE_STORE_IN_PROGESS = 10,
  EE_STORE_FAILED = 11,
  EE_STORE_SUCCESS = 12,
} EE_STATES;

/***** EE Variables *************************************************/
#define EEVARIABLES

typedef struct {
  uint32_T WriteCnt;                  /* Write Count: Identifies active Copy 	*/
  uint32_T EE_UniqID;
  uint8_T raptorFaultNonVolatileBits[11];/* Type : uint8_T, Storage : EEPROM */
  real32_T KeySwHiTimeThr;             /* Type : real32_T, Storage : CAL */
  real32_T KeySwLoTimeThr;             /* Type : real32_T, Storage : CAL */
  real32_T UpperFanPoint;              /* Type : real32_T, Storage : CAL */
  real32_T LowerFanPoint;              /* Type : real32_T, Storage : CAL */
  real32_T Vehicle_direction;          /* Type : real32_T, Storage : CAL */
  real32_T RPM[33];                    /* Type : real32_T, Storage : CAL */
  real32_T MaxTorqueMap[33];           /* Type : real32_T, Storage : CAL */
  real32_T tempRateFault;              /* Type : real32_T, Storage : CAL */
  uint32_T eradicTemp_X_Limit;         /* Type : uint32_T, Storage : CAL */
  uint32_T eradicTemp_Y_Limit;         /* Type : uint32_T, Storage : CAL */
  uint32_T tempSenseOC_X_Limit;        /* Type : uint32_T, Storage : CAL */
  uint32_T tempSenseOC_Y_Limit;        /* Type : uint32_T, Storage : CAL */
  uint32_T tempSenseSC_X_Limit;        /* Type : uint32_T, Storage : CAL */
  uint32_T tempSenseSC_Y_Limit;        /* Type : uint32_T, Storage : CAL */
  uint32_T tempHigh_X_Limit;           /* Type : uint32_T, Storage : CAL */
  uint32_T tempHigh_Y_Limit;           /* Type : uint32_T, Storage : CAL */
  uint32_T Throttle_plausibility_X_Limit;/* Type : uint32_T, Storage : CAL */
  uint32_T Throttle_plausibility_Y_Limit;/* Type : uint32_T, Storage : CAL */
  uint32_T Fan_PWM_freq;               /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputHi_X_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputHi_Y_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputLow_X_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT1_InputLow_Y_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputHi_X_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputHi_Y_Limit;       /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputLow_X_Limit;      /* Type : uint32_T, Storage : CAL */
  uint32_T POT2_InputLow_Y_Limit;      /* Type : uint32_T, Storage : CAL */
  real32_T Cooling_pump_PWM_D;         /* Type : real32_T, Storage : CAL */
  uint32_T Pump_PWM_freq;              /* Type : uint32_T, Storage : CAL */
  real32_T lowFlowRateFault;           /* Type : real32_T, Storage : CAL */
  uint32_T lowFlowRate_X_Limit;        /* Type : uint32_T, Storage : CAL */
  uint32_T lowFlowRate_Y_Limit;        /* Type : uint32_T, Storage : CAL */
  real32_T eradicFlowRateFault;        /* Type : real32_T, Storage : CAL */
  uint32_T eradicFlow_X_Limit;         /* Type : uint32_T, Storage : CAL */
  uint32_T eradicFlow_Y_Limit;         /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_BC_ID;            /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_RX_ID;            /* Type : uint32_T, Storage : CAL */
  uint32_T CAN1__XCP_TX_ID;            /* Type : uint32_T, Storage : CAL */
  uint8_T INPUT29_ADCMon_HoldCount;    /* Type : uint8_T, Storage : CAL */
  uint16_T CAN1__XCP_Security;         /* Type : uint16_T, Storage : CAL */
  uint16_T CAN1_Startup_Delay;         /* Type : uint16_T, Storage : CAL */
  uint8_T CAN1_ErrorCheck_Interval;    /* Type : uint8_T, Storage : CAL */
  uint8_T CAN1_ErrorPassive_Delay;     /* Type : uint8_T, Storage : CAL */
  uint16_T CAN2_Startup_Delay;         /* Type : uint16_T, Storage : CAL */
  uint8_T CAN2_ErrorCheck_Interval;    /* Type : uint8_T, Storage : CAL */
  uint8_T CAN2_ErrorPassive_Delay;     /* Type : uint8_T, Storage : CAL */
  E_FaultOperation raptorFaultOperation[11];
                                    /* Type : E_FaultOperation, Storage : CAL */
  uint8_T InjCDrv_EndOfStart;          /* Type : uint8_T, Storage : CAL */
  uint8_T EndOfStart;                  /* Type : uint8_T, Storage : CAL */
  uint16_T CRC;
         /* CRC - Last two bytes per SDK spec for CRC Calc (Parker Specific) 	*/
} EEVariables_T;

extern const EEVariables_T EEVariables_DEFAULT;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern EEVariables_T EEVariables_RAMShadow;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void App_EE_WriteAsync(uint8_T);
extern uint16_T Reset_xHistBuf[8] __attribute__ ((asection(".bss.earlycleared",
  "f=aw")));
extern struct Reset_Environment Reset_Env;
extern void App_EE_Store(void);
extern void App_EE_Defaults(void);
typedef struct {
  uint8_T INIT_RAM_EditVariables;
  real32_T APP_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T APP_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T APP_default_err_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T APP_default_err_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T Direction_cmd_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T Direction_cmd_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T POT1_InputHi_Override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT1_InputHi_Override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T POT1_InputLow_Override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT1_InputLow_Override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T POT1_ADC_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT1_ADC_OvrSts;/* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T POT1_OvrVal;/* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T POT1_OvrSts;    /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T APP1_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T APP1_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T POT2_InputHi_Override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT2_InputHi_Override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T POT2_InputLow_Override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT2_InputLow_Override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T POT2_ADC_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T POT2_ADC_OvrSts;/* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T POT2_OvrVal;/* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T POT2_OvrSts;    /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T APP2_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T APP2_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Starter_button_raw_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Starter_button_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T Safety_loop_error_raw_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Safety_loop_error_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Starter_button_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Starter_button_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Precharge_raw_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Precharge_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Charge_mode_raw_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Charge_mode_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Cooling_fault_any_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Cooling_fault_any_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Drive_enable_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Drive_enable_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T Inverter_enb_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Inverter_enb_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T RPM_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T RPM_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T Torque_map_val_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T Torque_map_val_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T Torque_cmd_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T Torque_cmd_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T RTDS_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T RTDS_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T TSMS_ADC_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T TSMS_ADC_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T IMD_GLV_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T IMD_GLV_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  boolean_T IMD_OkHs_override_OvrVal;
                       /* Type : boolean_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T IMD_OkHs_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T Temp_adc_raw_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Temp_adc_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T Temp_resistance_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T Temp_resistance_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  real32_T Temp_actual_celsius_override_OvrVal;
                       /* Type : real32_T,  Init_Value : 0.0, Storage : RAM,  */
  uint8_T Temp_actual_celsius_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T Fan_PWM_D_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Fan_PWM_D_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T GLV_hall_out_raw_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T GLV_hall_out_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint32_T Flowrate_hz_corrected_override_OvrVal;
                        /* Type : uint32_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Flowrate_hz_corrected_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint32_T Flow_rate_gpm_override_OvrVal;
                        /* Type : uint32_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T Flow_rate_gpm_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
  uint16_T BMS_SOC_raw_override_OvrVal;
                        /* Type : uint16_T,  Init_Value : 0U, Storage : RAM,  */
  uint8_T BMS_SOC_raw_override_OvrSts;
                          /* Type : uint8_T,  Init_Value : 0, Storage : RAM,  */
} RAMEditVariables_T;

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern RAMEditVariables_T RAMEditVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

extern void initRAMEditVariables(void);

/***** #DEFINES Accessors *************************************************/
#define FgndTasksStopped_Data()        (RAMVariables.FgndTasksStopped)
#define FgndTasksStopped_Ptr()         (&(RAMVariables.FgndTasksStopped))
#define FgndTasksStopped_ELEMENTS()    (1 * 1)
#define KeySwHiTimeThr_Data()          (EEVariables_RAMShadow.KeySwHiTimeThr)
#define KeySwHiTimeThr_Ptr()           (&(EEVariables_RAMShadow.KeySwHiTimeThr))
#define KeySwHiTimeThr_ELEMENTS()      (1 * 1)
#define KeySwLoTimeThr_Data()          (EEVariables_RAMShadow.KeySwLoTimeThr)
#define KeySwLoTimeThr_Ptr()           (&(EEVariables_RAMShadow.KeySwLoTimeThr))
#define KeySwLoTimeThr_ELEMENTS()      (1 * 1)
#define KeySw_Bgnd_Data()              (RAMVariables.KeySw_Bgnd)
#define KeySw_Bgnd_Ptr()               (&(RAMVariables.KeySw_Bgnd))
#define KeySw_Bgnd_ELEMENTS()          (1 * 1)
#define KeepModuleOn_Data()            (RAMVariables.KeepModuleOn)
#define KeepModuleOn_Ptr()             (&(RAMVariables.KeepModuleOn))
#define KeepModuleOn_ELEMENTS()        (1 * 1)
#define AbsoluteTime_Data()            (RAMVariables.AbsoluteTime)
#define AbsoluteTime_Ptr()             (&(RAMVariables.AbsoluteTime))
#define AbsoluteTime_ELEMENTS()        (1 * 1)
#define UpperFanPoint_Data()           (EEVariables_RAMShadow.UpperFanPoint)
#define UpperFanPoint_Ptr()            (&(EEVariables_RAMShadow.UpperFanPoint))
#define UpperFanPoint_ELEMENTS()       (1 * 1)
#define LowerFanPoint_Data()           (EEVariables_RAMShadow.LowerFanPoint)
#define LowerFanPoint_Ptr()            (&(EEVariables_RAMShadow.LowerFanPoint))
#define LowerFanPoint_ELEMENTS()       (1 * 1)
#define APP_override_OvrVal_Data()     (RAMEditVariables.APP_override_OvrVal)
#define APP_override_OvrVal_Ptr()      (&(RAMEditVariables.APP_override_OvrVal))
#define APP_override_OvrVal_ELEMENTS() (1 * 1)
#define APP_override_OvrSts_Data()     (RAMEditVariables.APP_override_OvrSts)
#define APP_override_OvrSts_Ptr()      (&(RAMEditVariables.APP_override_OvrSts))
#define APP_override_OvrSts_ELEMENTS() (1 * 1)
#define APP_default_err_override_OvrVal_Data() (RAMEditVariables.APP_default_err_override_OvrVal)
#define APP_default_err_override_OvrVal_Ptr() (&(RAMEditVariables.APP_default_err_override_OvrVal))
#define APP_default_err_override_OvrVal_ELEMENTS() (1 * 1)
#define APP_default_err_override_OvrSts_Data() (RAMEditVariables.APP_default_err_override_OvrSts)
#define APP_default_err_override_OvrSts_Ptr() (&(RAMEditVariables.APP_default_err_override_OvrSts))
#define APP_default_err_override_OvrSts_ELEMENTS() (1 * 1)
#define Vehicle_direction_Data()       (EEVariables_RAMShadow.Vehicle_direction)
#define Vehicle_direction_Ptr()        (&(EEVariables_RAMShadow.Vehicle_direction))
#define Vehicle_direction_ELEMENTS()   (1 * 1)
#define Direction_cmd_override_OvrVal_Data() (RAMEditVariables.Direction_cmd_override_OvrVal)
#define Direction_cmd_override_OvrVal_Ptr() (&(RAMEditVariables.Direction_cmd_override_OvrVal))
#define Direction_cmd_override_OvrVal_ELEMENTS() (1 * 1)
#define Direction_cmd_override_OvrSts_Data() (RAMEditVariables.Direction_cmd_override_OvrSts)
#define Direction_cmd_override_OvrSts_Ptr() (&(RAMEditVariables.Direction_cmd_override_OvrSts))
#define Direction_cmd_override_OvrSts_ELEMENTS() (1 * 1)
#define POT1_InputHi_Override_OvrVal_Data() (RAMEditVariables.POT1_InputHi_Override_OvrVal)
#define POT1_InputHi_Override_OvrVal_Ptr() (&(RAMEditVariables.POT1_InputHi_Override_OvrVal))
#define POT1_InputHi_Override_OvrVal_ELEMENTS() (1 * 1)
#define POT1_InputHi_Override_Data()   (RAMVariables.POT1_InputHi_Override)
#define POT1_InputHi_Override_Ptr()    (&(RAMVariables.POT1_InputHi_Override))
#define POT1_InputHi_Override_ELEMENTS() (1 * 1)
#define POT1_InputHi_Override_OvrSts_Data() (RAMEditVariables.POT1_InputHi_Override_OvrSts)
#define POT1_InputHi_Override_OvrSts_Ptr() (&(RAMEditVariables.POT1_InputHi_Override_OvrSts))
#define POT1_InputHi_Override_OvrSts_ELEMENTS() (1 * 1)
#define POT1_InputLow_Override_OvrVal_Data() (RAMEditVariables.POT1_InputLow_Override_OvrVal)
#define POT1_InputLow_Override_OvrVal_Ptr() (&(RAMEditVariables.POT1_InputLow_Override_OvrVal))
#define POT1_InputLow_Override_OvrVal_ELEMENTS() (1 * 1)
#define POT1_InputLow_Override_Data()  (RAMVariables.POT1_InputLow_Override)
#define POT1_InputLow_Override_Ptr()   (&(RAMVariables.POT1_InputLow_Override))
#define POT1_InputLow_Override_ELEMENTS() (1 * 1)
#define POT1_InputLow_Override_OvrSts_Data() (RAMEditVariables.POT1_InputLow_Override_OvrSts)
#define POT1_InputLow_Override_OvrSts_Ptr() (&(RAMEditVariables.POT1_InputLow_Override_OvrSts))
#define POT1_InputLow_Override_OvrSts_ELEMENTS() (1 * 1)
#define POT1_ADC_OvrVal_Data()         (RAMEditVariables.POT1_ADC_OvrVal)
#define POT1_ADC_OvrVal_Ptr()          (&(RAMEditVariables.POT1_ADC_OvrVal))
#define POT1_ADC_OvrVal_ELEMENTS()     (1 * 1)
#define POT1_ADC_Data()                (RAMVariables.POT1_ADC)
#define POT1_ADC_Ptr()                 (&(RAMVariables.POT1_ADC))
#define POT1_ADC_ELEMENTS()            (1 * 1)
#define POT1_ADC_OvrSts_Data()         (RAMEditVariables.POT1_ADC_OvrSts)
#define POT1_ADC_OvrSts_Ptr()          (&(RAMEditVariables.POT1_ADC_OvrSts))
#define POT1_ADC_OvrSts_ELEMENTS()     (1 * 1)
#define POT1_ADCHiPT_Data()            (CONSTVariables.POT1_ADCHiPT)
#define POT1_ADCHiPT_Ptr()             (&(CONSTVariables.POT1_ADCHiPT))
#define POT1_ADCHiPT_ELEMENTS()        (1 * 1)
#define POT1_ADCLoPT_Data()            (CONSTVariables.POT1_ADCLoPT)
#define POT1_ADCLoPT_Ptr()             (&(CONSTVariables.POT1_ADCLoPT))
#define POT1_ADCLoPT_ELEMENTS()        (1 * 1)
#define POT1_OvrVal_Data()             (RAMEditVariables.POT1_OvrVal)
#define POT1_OvrVal_Ptr()              (&(RAMEditVariables.POT1_OvrVal))
#define POT1_OvrVal_ELEMENTS()         (1 * 1)
#define POT1_Data()                    (RAMVariables.POT1)
#define POT1_Ptr()                     (&(RAMVariables.POT1))
#define POT1_ELEMENTS()                (1 * 1)
#define POT1_OvrSts_Data()             (RAMEditVariables.POT1_OvrSts)
#define POT1_OvrSts_Ptr()              (&(RAMEditVariables.POT1_OvrSts))
#define POT1_OvrSts_ELEMENTS()         (1 * 1)
#define APP1_override_OvrVal_Data()    (RAMEditVariables.APP1_override_OvrVal)
#define APP1_override_OvrVal_Ptr()     (&(RAMEditVariables.APP1_override_OvrVal))
#define APP1_override_OvrVal_ELEMENTS() (1 * 1)
#define APP1_override_OvrSts_Data()    (RAMEditVariables.APP1_override_OvrSts)
#define APP1_override_OvrSts_Ptr()     (&(RAMEditVariables.APP1_override_OvrSts))
#define APP1_override_OvrSts_ELEMENTS() (1 * 1)
#define POT2_InputHi_Override_OvrVal_Data() (RAMEditVariables.POT2_InputHi_Override_OvrVal)
#define POT2_InputHi_Override_OvrVal_Ptr() (&(RAMEditVariables.POT2_InputHi_Override_OvrVal))
#define POT2_InputHi_Override_OvrVal_ELEMENTS() (1 * 1)
#define POT2_InputHi_Override_Data()   (RAMVariables.POT2_InputHi_Override)
#define POT2_InputHi_Override_Ptr()    (&(RAMVariables.POT2_InputHi_Override))
#define POT2_InputHi_Override_ELEMENTS() (1 * 1)
#define POT2_InputHi_Override_OvrSts_Data() (RAMEditVariables.POT2_InputHi_Override_OvrSts)
#define POT2_InputHi_Override_OvrSts_Ptr() (&(RAMEditVariables.POT2_InputHi_Override_OvrSts))
#define POT2_InputHi_Override_OvrSts_ELEMENTS() (1 * 1)
#define POT2_InputLow_Override_OvrVal_Data() (RAMEditVariables.POT2_InputLow_Override_OvrVal)
#define POT2_InputLow_Override_OvrVal_Ptr() (&(RAMEditVariables.POT2_InputLow_Override_OvrVal))
#define POT2_InputLow_Override_OvrVal_ELEMENTS() (1 * 1)
#define POT2_InputLow_Override_Data()  (RAMVariables.POT2_InputLow_Override)
#define POT2_InputLow_Override_Ptr()   (&(RAMVariables.POT2_InputLow_Override))
#define POT2_InputLow_Override_ELEMENTS() (1 * 1)
#define POT2_InputLow_Override_OvrSts_Data() (RAMEditVariables.POT2_InputLow_Override_OvrSts)
#define POT2_InputLow_Override_OvrSts_Ptr() (&(RAMEditVariables.POT2_InputLow_Override_OvrSts))
#define POT2_InputLow_Override_OvrSts_ELEMENTS() (1 * 1)
#define POT2_ADC_OvrVal_Data()         (RAMEditVariables.POT2_ADC_OvrVal)
#define POT2_ADC_OvrVal_Ptr()          (&(RAMEditVariables.POT2_ADC_OvrVal))
#define POT2_ADC_OvrVal_ELEMENTS()     (1 * 1)
#define POT2_ADC_Data()                (RAMVariables.POT2_ADC)
#define POT2_ADC_Ptr()                 (&(RAMVariables.POT2_ADC))
#define POT2_ADC_ELEMENTS()            (1 * 1)
#define POT2_ADC_OvrSts_Data()         (RAMEditVariables.POT2_ADC_OvrSts)
#define POT2_ADC_OvrSts_Ptr()          (&(RAMEditVariables.POT2_ADC_OvrSts))
#define POT2_ADC_OvrSts_ELEMENTS()     (1 * 1)
#define POT2_ADCHiPT_Data()            (CONSTVariables.POT2_ADCHiPT)
#define POT2_ADCHiPT_Ptr()             (&(CONSTVariables.POT2_ADCHiPT))
#define POT2_ADCHiPT_ELEMENTS()        (1 * 1)
#define POT2_ADCLoPT_Data()            (CONSTVariables.POT2_ADCLoPT)
#define POT2_ADCLoPT_Ptr()             (&(CONSTVariables.POT2_ADCLoPT))
#define POT2_ADCLoPT_ELEMENTS()        (1 * 1)
#define POT2_OvrVal_Data()             (RAMEditVariables.POT2_OvrVal)
#define POT2_OvrVal_Ptr()              (&(RAMEditVariables.POT2_OvrVal))
#define POT2_OvrVal_ELEMENTS()         (1 * 1)
#define POT2_Data()                    (RAMVariables.POT2)
#define POT2_Ptr()                     (&(RAMVariables.POT2))
#define POT2_ELEMENTS()                (1 * 1)
#define POT2_OvrSts_Data()             (RAMEditVariables.POT2_OvrSts)
#define POT2_OvrSts_Ptr()              (&(RAMEditVariables.POT2_OvrSts))
#define POT2_OvrSts_ELEMENTS()         (1 * 1)
#define APP2_override_OvrVal_Data()    (RAMEditVariables.APP2_override_OvrVal)
#define APP2_override_OvrVal_Ptr()     (&(RAMEditVariables.APP2_override_OvrVal))
#define APP2_override_OvrVal_ELEMENTS() (1 * 1)
#define APP2_override_OvrSts_Data()    (RAMEditVariables.APP2_override_OvrSts)
#define APP2_override_OvrSts_Ptr()     (&(RAMEditVariables.APP2_override_OvrSts))
#define APP2_override_OvrSts_ELEMENTS() (1 * 1)
#define Starter_button_raw_override_OvrVal_Data() (RAMEditVariables.Starter_button_raw_override_OvrVal)
#define Starter_button_raw_override_OvrVal_Ptr() (&(RAMEditVariables.Starter_button_raw_override_OvrVal))
#define Starter_button_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define Starter_button_raw_override_OvrSts_Data() (RAMEditVariables.Starter_button_raw_override_OvrSts)
#define Starter_button_raw_override_OvrSts_Ptr() (&(RAMEditVariables.Starter_button_raw_override_OvrSts))
#define Starter_button_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define Safety_loop_error_raw_override_OvrVal_Data() (RAMEditVariables.Safety_loop_error_raw_override_OvrVal)
#define Safety_loop_error_raw_override_OvrVal_Ptr() (&(RAMEditVariables.Safety_loop_error_raw_override_OvrVal))
#define Safety_loop_error_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define Safety_loop_error_raw_override_OvrSts_Data() (RAMEditVariables.Safety_loop_error_raw_override_OvrSts)
#define Safety_loop_error_raw_override_OvrSts_Ptr() (&(RAMEditVariables.Safety_loop_error_raw_override_OvrSts))
#define Safety_loop_error_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define Starter_button_override_OvrVal_Data() (RAMEditVariables.Starter_button_override_OvrVal)
#define Starter_button_override_OvrVal_Ptr() (&(RAMEditVariables.Starter_button_override_OvrVal))
#define Starter_button_override_OvrVal_ELEMENTS() (1 * 1)
#define Starter_button_override_OvrSts_Data() (RAMEditVariables.Starter_button_override_OvrSts)
#define Starter_button_override_OvrSts_Ptr() (&(RAMEditVariables.Starter_button_override_OvrSts))
#define Starter_button_override_OvrSts_ELEMENTS() (1 * 1)
#define Precharge_raw_override_OvrVal_Data() (RAMEditVariables.Precharge_raw_override_OvrVal)
#define Precharge_raw_override_OvrVal_Ptr() (&(RAMEditVariables.Precharge_raw_override_OvrVal))
#define Precharge_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define Precharge_raw_override_OvrSts_Data() (RAMEditVariables.Precharge_raw_override_OvrSts)
#define Precharge_raw_override_OvrSts_Ptr() (&(RAMEditVariables.Precharge_raw_override_OvrSts))
#define Precharge_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define Charge_mode_raw_override_OvrVal_Data() (RAMEditVariables.Charge_mode_raw_override_OvrVal)
#define Charge_mode_raw_override_OvrVal_Ptr() (&(RAMEditVariables.Charge_mode_raw_override_OvrVal))
#define Charge_mode_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define Charge_mode_raw_override_OvrSts_Data() (RAMEditVariables.Charge_mode_raw_override_OvrSts)
#define Charge_mode_raw_override_OvrSts_Ptr() (&(RAMEditVariables.Charge_mode_raw_override_OvrSts))
#define Charge_mode_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define Cooling_fault_any_override_OvrVal_Data() (RAMEditVariables.Cooling_fault_any_override_OvrVal)
#define Cooling_fault_any_override_OvrVal_Ptr() (&(RAMEditVariables.Cooling_fault_any_override_OvrVal))
#define Cooling_fault_any_override_OvrVal_ELEMENTS() (1 * 1)
#define Cooling_fault_any_override_OvrSts_Data() (RAMEditVariables.Cooling_fault_any_override_OvrSts)
#define Cooling_fault_any_override_OvrSts_Ptr() (&(RAMEditVariables.Cooling_fault_any_override_OvrSts))
#define Cooling_fault_any_override_OvrSts_ELEMENTS() (1 * 1)
#define Drive_enable_override_OvrVal_Data() (RAMEditVariables.Drive_enable_override_OvrVal)
#define Drive_enable_override_OvrVal_Ptr() (&(RAMEditVariables.Drive_enable_override_OvrVal))
#define Drive_enable_override_OvrVal_ELEMENTS() (1 * 1)
#define Drive_enable_override_OvrSts_Data() (RAMEditVariables.Drive_enable_override_OvrSts)
#define Drive_enable_override_OvrSts_Ptr() (&(RAMEditVariables.Drive_enable_override_OvrSts))
#define Drive_enable_override_OvrSts_ELEMENTS() (1 * 1)
#define Inverter_enb_override_OvrVal_Data() (RAMEditVariables.Inverter_enb_override_OvrVal)
#define Inverter_enb_override_OvrVal_Ptr() (&(RAMEditVariables.Inverter_enb_override_OvrVal))
#define Inverter_enb_override_OvrVal_ELEMENTS() (1 * 1)
#define Inverter_enb_override_OvrSts_Data() (RAMEditVariables.Inverter_enb_override_OvrSts)
#define Inverter_enb_override_OvrSts_Ptr() (&(RAMEditVariables.Inverter_enb_override_OvrSts))
#define Inverter_enb_override_OvrSts_ELEMENTS() (1 * 1)
#define RPM_override_OvrVal_Data()     (RAMEditVariables.RPM_override_OvrVal)
#define RPM_override_OvrVal_Ptr()      (&(RAMEditVariables.RPM_override_OvrVal))
#define RPM_override_OvrVal_ELEMENTS() (1 * 1)
#define RPM_override_OvrSts_Data()     (RAMEditVariables.RPM_override_OvrSts)
#define RPM_override_OvrSts_Ptr()      (&(RAMEditVariables.RPM_override_OvrSts))
#define RPM_override_OvrSts_ELEMENTS() (1 * 1)
#define RPM_IN_Data()                  (RAMVariables.RPM_IN)
#define RPM_IN_Ptr()                   (&(RAMVariables.RPM_IN))
#define RPM_IN_ELEMENTS()              (1 * 1)
#define RPM_Data()                     (EEVariables_RAMShadow.RPM)
#define RPM_Ptr()                      (&(EEVariables_RAMShadow.RPM))
#define RPM_ELEMENTS()                 (1 * 33)
#define MaxTorqueMap_Data()            (EEVariables_RAMShadow.MaxTorqueMap)
#define MaxTorqueMap_Ptr()             (&(EEVariables_RAMShadow.MaxTorqueMap))
#define MaxTorqueMap_ELEMENTS()        (1 * 33)
#define MaxTorqueMap_Y_IN_IDX_Data()   (RAMVariables.MaxTorqueMap_Y_IN_IDX)
#define MaxTorqueMap_Y_IN_IDX_Ptr()    (&(RAMVariables.MaxTorqueMap_Y_IN_IDX))
#define MaxTorqueMap_Y_IN_IDX_ELEMENTS() (1 * 1)
#define Torque_map_val_override_OvrVal_Data() (RAMEditVariables.Torque_map_val_override_OvrVal)
#define Torque_map_val_override_OvrVal_Ptr() (&(RAMEditVariables.Torque_map_val_override_OvrVal))
#define Torque_map_val_override_OvrVal_ELEMENTS() (1 * 1)
#define Torque_map_val_override_OvrSts_Data() (RAMEditVariables.Torque_map_val_override_OvrSts)
#define Torque_map_val_override_OvrSts_Ptr() (&(RAMEditVariables.Torque_map_val_override_OvrSts))
#define Torque_map_val_override_OvrSts_ELEMENTS() (1 * 1)
#define Torque_cmd_override_OvrVal_Data() (RAMEditVariables.Torque_cmd_override_OvrVal)
#define Torque_cmd_override_OvrVal_Ptr() (&(RAMEditVariables.Torque_cmd_override_OvrVal))
#define Torque_cmd_override_OvrVal_ELEMENTS() (1 * 1)
#define Torque_cmd_override_OvrSts_Data() (RAMEditVariables.Torque_cmd_override_OvrSts)
#define Torque_cmd_override_OvrSts_Ptr() (&(RAMEditVariables.Torque_cmd_override_OvrSts))
#define Torque_cmd_override_OvrSts_ELEMENTS() (1 * 1)
#define Torque_cmd_Data()              (RAMVariables.Torque_cmd)
#define Torque_cmd_Ptr()               (&(RAMVariables.Torque_cmd))
#define Torque_cmd_ELEMENTS()          (1 * 1)
#define Direction_cmd_Data()           (RAMVariables.Direction_cmd)
#define Direction_cmd_Ptr()            (&(RAMVariables.Direction_cmd))
#define Direction_cmd_ELEMENTS()       (1 * 1)
#define RTDS_override_OvrVal_Data()    (RAMEditVariables.RTDS_override_OvrVal)
#define RTDS_override_OvrVal_Ptr()     (&(RAMEditVariables.RTDS_override_OvrVal))
#define RTDS_override_OvrVal_ELEMENTS() (1 * 1)
#define RTDS_override_OvrSts_Data()    (RAMEditVariables.RTDS_override_OvrSts)
#define RTDS_override_OvrSts_Ptr()     (&(RAMEditVariables.RTDS_override_OvrSts))
#define RTDS_override_OvrSts_ELEMENTS() (1 * 1)
#define TSMS_ADC_override_OvrVal_Data() (RAMEditVariables.TSMS_ADC_override_OvrVal)
#define TSMS_ADC_override_OvrVal_Ptr() (&(RAMEditVariables.TSMS_ADC_override_OvrVal))
#define TSMS_ADC_override_OvrVal_ELEMENTS() (1 * 1)
#define TSMS_ADC_override_OvrSts_Data() (RAMEditVariables.TSMS_ADC_override_OvrSts)
#define TSMS_ADC_override_OvrSts_Ptr() (&(RAMEditVariables.TSMS_ADC_override_OvrSts))
#define TSMS_ADC_override_OvrSts_ELEMENTS() (1 * 1)
#define IMD_GLV_override_OvrVal_Data() (RAMEditVariables.IMD_GLV_override_OvrVal)
#define IMD_GLV_override_OvrVal_Ptr()  (&(RAMEditVariables.IMD_GLV_override_OvrVal))
#define IMD_GLV_override_OvrVal_ELEMENTS() (1 * 1)
#define IMD_GLV_override_OvrSts_Data() (RAMEditVariables.IMD_GLV_override_OvrSts)
#define IMD_GLV_override_OvrSts_Ptr()  (&(RAMEditVariables.IMD_GLV_override_OvrSts))
#define IMD_GLV_override_OvrSts_ELEMENTS() (1 * 1)
#define IMD_OkHs_override_OvrVal_Data() (RAMEditVariables.IMD_OkHs_override_OvrVal)
#define IMD_OkHs_override_OvrVal_Ptr() (&(RAMEditVariables.IMD_OkHs_override_OvrVal))
#define IMD_OkHs_override_OvrVal_ELEMENTS() (1 * 1)
#define IMD_OkHs_override_OvrSts_Data() (RAMEditVariables.IMD_OkHs_override_OvrSts)
#define IMD_OkHs_override_OvrSts_Ptr() (&(RAMEditVariables.IMD_OkHs_override_OvrSts))
#define IMD_OkHs_override_OvrSts_ELEMENTS() (1 * 1)
#define Temp_adc_raw_override_OvrVal_Data() (RAMEditVariables.Temp_adc_raw_override_OvrVal)
#define Temp_adc_raw_override_OvrVal_Ptr() (&(RAMEditVariables.Temp_adc_raw_override_OvrVal))
#define Temp_adc_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define Temp_adc_raw_override_OvrSts_Data() (RAMEditVariables.Temp_adc_raw_override_OvrSts)
#define Temp_adc_raw_override_OvrSts_Ptr() (&(RAMEditVariables.Temp_adc_raw_override_OvrSts))
#define Temp_adc_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define Temp_resistance_override_OvrVal_Data() (RAMEditVariables.Temp_resistance_override_OvrVal)
#define Temp_resistance_override_OvrVal_Ptr() (&(RAMEditVariables.Temp_resistance_override_OvrVal))
#define Temp_resistance_override_OvrVal_ELEMENTS() (1 * 1)
#define Temp_resistance_override_OvrSts_Data() (RAMEditVariables.Temp_resistance_override_OvrSts)
#define Temp_resistance_override_OvrSts_Ptr() (&(RAMEditVariables.Temp_resistance_override_OvrSts))
#define Temp_resistance_override_OvrSts_ELEMENTS() (1 * 1)
#define Temp_actual_celsius_override_OvrVal_Data() (RAMEditVariables.Temp_actual_celsius_override_OvrVal)
#define Temp_actual_celsius_override_OvrVal_Ptr() (&(RAMEditVariables.Temp_actual_celsius_override_OvrVal))
#define Temp_actual_celsius_override_OvrVal_ELEMENTS() (1 * 1)
#define Temp_actual_celsius_override_OvrSts_Data() (RAMEditVariables.Temp_actual_celsius_override_OvrSts)
#define Temp_actual_celsius_override_OvrSts_Ptr() (&(RAMEditVariables.Temp_actual_celsius_override_OvrSts))
#define Temp_actual_celsius_override_OvrSts_ELEMENTS() (1 * 1)
#define tempRateFault_Data()           (EEVariables_RAMShadow.tempRateFault)
#define tempRateFault_Ptr()            (&(EEVariables_RAMShadow.tempRateFault))
#define tempRateFault_ELEMENTS()       (1 * 1)
#define eradicTemp_X_Limit_Data()      (EEVariables_RAMShadow.eradicTemp_X_Limit)
#define eradicTemp_X_Limit_Ptr()       (&(EEVariables_RAMShadow.eradicTemp_X_Limit))
#define eradicTemp_X_Limit_ELEMENTS()  (1 * 1)
#define eradicTemp_Y_Limit_Data()      (EEVariables_RAMShadow.eradicTemp_Y_Limit)
#define eradicTemp_Y_Limit_Ptr()       (&(EEVariables_RAMShadow.eradicTemp_Y_Limit))
#define eradicTemp_Y_Limit_ELEMENTS()  (1 * 1)
#define tempSenseOC_X_Limit_Data()     (EEVariables_RAMShadow.tempSenseOC_X_Limit)
#define tempSenseOC_X_Limit_Ptr()      (&(EEVariables_RAMShadow.tempSenseOC_X_Limit))
#define tempSenseOC_X_Limit_ELEMENTS() (1 * 1)
#define tempSenseOC_Y_Limit_Data()     (EEVariables_RAMShadow.tempSenseOC_Y_Limit)
#define tempSenseOC_Y_Limit_Ptr()      (&(EEVariables_RAMShadow.tempSenseOC_Y_Limit))
#define tempSenseOC_Y_Limit_ELEMENTS() (1 * 1)
#define tempSenseSC_X_Limit_Data()     (EEVariables_RAMShadow.tempSenseSC_X_Limit)
#define tempSenseSC_X_Limit_Ptr()      (&(EEVariables_RAMShadow.tempSenseSC_X_Limit))
#define tempSenseSC_X_Limit_ELEMENTS() (1 * 1)
#define tempSenseSC_Y_Limit_Data()     (EEVariables_RAMShadow.tempSenseSC_Y_Limit)
#define tempSenseSC_Y_Limit_Ptr()      (&(EEVariables_RAMShadow.tempSenseSC_Y_Limit))
#define tempSenseSC_Y_Limit_ELEMENTS() (1 * 1)
#define tempHigh_X_Limit_Data()        (EEVariables_RAMShadow.tempHigh_X_Limit)
#define tempHigh_X_Limit_Ptr()         (&(EEVariables_RAMShadow.tempHigh_X_Limit))
#define tempHigh_X_Limit_ELEMENTS()    (1 * 1)
#define tempHigh_Y_Limit_Data()        (EEVariables_RAMShadow.tempHigh_Y_Limit)
#define tempHigh_Y_Limit_Ptr()         (&(EEVariables_RAMShadow.tempHigh_Y_Limit))
#define tempHigh_Y_Limit_ELEMENTS()    (1 * 1)
#define Throttle_plausibility_X_Limit_Data() (EEVariables_RAMShadow.Throttle_plausibility_X_Limit)
#define Throttle_plausibility_X_Limit_Ptr() (&(EEVariables_RAMShadow.Throttle_plausibility_X_Limit))
#define Throttle_plausibility_X_Limit_ELEMENTS() (1 * 1)
#define Throttle_plausibility_Y_Limit_Data() (EEVariables_RAMShadow.Throttle_plausibility_Y_Limit)
#define Throttle_plausibility_Y_Limit_Ptr() (&(EEVariables_RAMShadow.Throttle_plausibility_Y_Limit))
#define Throttle_plausibility_Y_Limit_ELEMENTS() (1 * 1)
#define Precharge_status_Data()        (RAMVariables.Precharge_status)
#define Precharge_status_Ptr()         (&(RAMVariables.Precharge_status))
#define Precharge_status_ELEMENTS()    (1 * 1)
#define Starter_button_Data()          (RAMVariables.Starter_button)
#define Starter_button_Ptr()           (&(RAMVariables.Starter_button))
#define Starter_button_ELEMENTS()      (1 * 1)
#define Safety_loop_error_logic_Data() (RAMVariables.Safety_loop_error_logic)
#define Safety_loop_error_logic_Ptr()  (&(RAMVariables.Safety_loop_error_logic))
#define Safety_loop_error_logic_ELEMENTS() (1 * 1)
#define RTDS_Data()                    (RAMVariables.RTDS)
#define RTDS_Ptr()                     (&(RAMVariables.RTDS))
#define RTDS_ELEMENTS()                (1 * 1)
#define Temp_adc_raw_Data()            (RAMVariables.Temp_adc_raw)
#define Temp_adc_raw_Ptr()             (&(RAMVariables.Temp_adc_raw))
#define Temp_adc_raw_ELEMENTS()        (1 * 1)
#define Temp_resistance_Data()         (RAMVariables.Temp_resistance)
#define Temp_resistance_Ptr()          (&(RAMVariables.Temp_resistance))
#define Temp_resistance_ELEMENTS()     (1 * 1)
#define Cooling_fault_any_Data()       (RAMVariables.Cooling_fault_any)
#define Cooling_fault_any_Ptr()        (&(RAMVariables.Cooling_fault_any))
#define Cooling_fault_any_ELEMENTS()   (1 * 1)
#define Charge_mode_Data()             (RAMVariables.Charge_mode)
#define Charge_mode_Ptr()              (&(RAMVariables.Charge_mode))
#define Charge_mode_ELEMENTS()         (1 * 1)
#define Starter_button_latch_q_naught_Data() (RAMVariables.Starter_button_latch_q_naught)
#define Starter_button_latch_q_naught_Ptr() (&(RAMVariables.Starter_button_latch_q_naught))
#define Starter_button_latch_q_naught_ELEMENTS() (1 * 1)
#define fault_tempSenseOC_Data()       (RAMVariables.fault_tempSenseOC)
#define fault_tempSenseOC_Ptr()        (&(RAMVariables.fault_tempSenseOC))
#define fault_tempSenseOC_ELEMENTS()   (1 * 1)
#define fault_tempSenseSC_Data()       (RAMVariables.fault_tempSenseSC)
#define fault_tempSenseSC_Ptr()        (&(RAMVariables.fault_tempSenseSC))
#define fault_tempSenseSC_ELEMENTS()   (1 * 1)
#define fault_tempSenseHigh_Data()     (RAMVariables.fault_tempSenseHigh)
#define fault_tempSenseHigh_Ptr()      (&(RAMVariables.fault_tempSenseHigh))
#define fault_tempSenseHigh_ELEMENTS() (1 * 1)
#define fault_eradic_temp_Data()       (RAMVariables.fault_eradic_temp)
#define fault_eradic_temp_Ptr()        (&(RAMVariables.fault_eradic_temp))
#define fault_eradic_temp_ELEMENTS()   (1 * 1)
#define fault_lowFlowRate_Data()       (RAMVariables.fault_lowFlowRate)
#define fault_lowFlowRate_Ptr()        (&(RAMVariables.fault_lowFlowRate))
#define fault_lowFlowRate_ELEMENTS()   (1 * 1)
#define fault_eradicFlowRate_Data()    (RAMVariables.fault_eradicFlowRate)
#define fault_eradicFlowRate_Ptr()     (&(RAMVariables.fault_eradicFlowRate))
#define fault_eradicFlowRate_ELEMENTS() (1 * 1)
#define Temp_actual_celsius_Data()     (RAMVariables.Temp_actual_celsius)
#define Temp_actual_celsius_Ptr()      (&(RAMVariables.Temp_actual_celsius))
#define Temp_actual_celsius_ELEMENTS() (1 * 1)
#define Fan_PWM_D_override_OvrVal_Data() (RAMEditVariables.Fan_PWM_D_override_OvrVal)
#define Fan_PWM_D_override_OvrVal_Ptr() (&(RAMEditVariables.Fan_PWM_D_override_OvrVal))
#define Fan_PWM_D_override_OvrVal_ELEMENTS() (1 * 1)
#define Fan_PWM_D_override_OvrSts_Data() (RAMEditVariables.Fan_PWM_D_override_OvrSts)
#define Fan_PWM_D_override_OvrSts_Ptr() (&(RAMEditVariables.Fan_PWM_D_override_OvrSts))
#define Fan_PWM_D_override_OvrSts_ELEMENTS() (1 * 1)
#define Fan_PWM_D_Data()               (RAMVariables.Fan_PWM_D)
#define Fan_PWM_D_Ptr()                (&(RAMVariables.Fan_PWM_D))
#define Fan_PWM_D_ELEMENTS()           (1 * 1)
#define TSMS_logic_probe_Data()        (RAMVariables.TSMS_logic_probe)
#define TSMS_logic_probe_Ptr()         (&(RAMVariables.TSMS_logic_probe))
#define TSMS_logic_probe_ELEMENTS()    (1 * 1)
#define IMD_OkHs_probe_Data()          (RAMVariables.IMD_OkHs_probe)
#define IMD_OkHs_probe_Ptr()           (&(RAMVariables.IMD_OkHs_probe))
#define IMD_OkHs_probe_ELEMENTS()      (1 * 1)
#define IMD_GLV_probe_Data()           (RAMVariables.IMD_GLV_probe)
#define IMD_GLV_probe_Ptr()            (&(RAMVariables.IMD_GLV_probe))
#define IMD_GLV_probe_ELEMENTS()       (1 * 1)
#define RPM_val_Data()                 (RAMVariables.RPM_val)
#define RPM_val_Ptr()                  (&(RAMVariables.RPM_val))
#define RPM_val_ELEMENTS()             (1 * 1)
#define TP_val_Data()                  (RAMVariables.TP_val)
#define TP_val_Ptr()                   (&(RAMVariables.TP_val))
#define TP_val_ELEMENTS()              (1 * 1)
#define APP1_Data()                    (RAMVariables.APP1)
#define APP1_Ptr()                     (&(RAMVariables.APP1))
#define APP1_ELEMENTS()                (1 * 1)
#define APP2_Data()                    (RAMVariables.APP2)
#define APP2_Ptr()                     (&(RAMVariables.APP2))
#define APP2_ELEMENTS()                (1 * 1)
#define Throttle_plausibility_probe_Data() (RAMVariables.Throttle_plausibility_probe)
#define Throttle_plausibility_probe_Ptr() (&(RAMVariables.Throttle_plausibility_probe))
#define Throttle_plausibility_probe_ELEMENTS() (1 * 1)
#define Drive_enable_Data()            (RAMVariables.Drive_enable)
#define Drive_enable_Ptr()             (&(RAMVariables.Drive_enable))
#define Drive_enable_ELEMENTS()        (1 * 1)
#define Fan_PWM_freq_Data()            (EEVariables_RAMShadow.Fan_PWM_freq)
#define Fan_PWM_freq_Ptr()             (&(EEVariables_RAMShadow.Fan_PWM_freq))
#define Fan_PWM_freq_ELEMENTS()        (1 * 1)
#define POT1_InputHighThresh_Data()    (CONSTVariables.POT1_InputHighThresh)
#define POT1_InputHighThresh_Ptr()     (&(CONSTVariables.POT1_InputHighThresh))
#define POT1_InputHighThresh_ELEMENTS() (1 * 1)
#define POT1_InputHi_X_Limit_Data()    (EEVariables_RAMShadow.POT1_InputHi_X_Limit)
#define POT1_InputHi_X_Limit_Ptr()     (&(EEVariables_RAMShadow.POT1_InputHi_X_Limit))
#define POT1_InputHi_X_Limit_ELEMENTS() (1 * 1)
#define POT1_InputHi_Y_Limit_Data()    (EEVariables_RAMShadow.POT1_InputHi_Y_Limit)
#define POT1_InputHi_Y_Limit_Ptr()     (&(EEVariables_RAMShadow.POT1_InputHi_Y_Limit))
#define POT1_InputHi_Y_Limit_ELEMENTS() (1 * 1)
#define POT1_InputLowThresh_Data()     (CONSTVariables.POT1_InputLowThresh)
#define POT1_InputLowThresh_Ptr()      (&(CONSTVariables.POT1_InputLowThresh))
#define POT1_InputLowThresh_ELEMENTS() (1 * 1)
#define POT1_InputLow_X_Limit_Data()   (EEVariables_RAMShadow.POT1_InputLow_X_Limit)
#define POT1_InputLow_X_Limit_Ptr()    (&(EEVariables_RAMShadow.POT1_InputLow_X_Limit))
#define POT1_InputLow_X_Limit_ELEMENTS() (1 * 1)
#define POT1_InputLow_Y_Limit_Data()   (EEVariables_RAMShadow.POT1_InputLow_Y_Limit)
#define POT1_InputLow_Y_Limit_Ptr()    (&(EEVariables_RAMShadow.POT1_InputLow_Y_Limit))
#define POT1_InputLow_Y_Limit_ELEMENTS() (1 * 1)
#define POT1HighProbe_Data()           (RAMVariables.POT1HighProbe)
#define POT1HighProbe_Ptr()            (&(RAMVariables.POT1HighProbe))
#define POT1HighProbe_ELEMENTS()       (1 * 1)
#define POT1LowProbe_Data()            (RAMVariables.POT1LowProbe)
#define POT1LowProbe_Ptr()             (&(RAMVariables.POT1LowProbe))
#define POT1LowProbe_ELEMENTS()        (1 * 1)
#define POT1_ADC_Raw_Data()            (RAMVariables.POT1_ADC_Raw)
#define POT1_ADC_Raw_Ptr()             (&(RAMVariables.POT1_ADC_Raw))
#define POT1_ADC_Raw_ELEMENTS()        (1 * 1)
#define POT2_InputHighThresh_Data()    (CONSTVariables.POT2_InputHighThresh)
#define POT2_InputHighThresh_Ptr()     (&(CONSTVariables.POT2_InputHighThresh))
#define POT2_InputHighThresh_ELEMENTS() (1 * 1)
#define POT2_InputHi_X_Limit_Data()    (EEVariables_RAMShadow.POT2_InputHi_X_Limit)
#define POT2_InputHi_X_Limit_Ptr()     (&(EEVariables_RAMShadow.POT2_InputHi_X_Limit))
#define POT2_InputHi_X_Limit_ELEMENTS() (1 * 1)
#define POT2_InputHi_Y_Limit_Data()    (EEVariables_RAMShadow.POT2_InputHi_Y_Limit)
#define POT2_InputHi_Y_Limit_Ptr()     (&(EEVariables_RAMShadow.POT2_InputHi_Y_Limit))
#define POT2_InputHi_Y_Limit_ELEMENTS() (1 * 1)
#define POT2_InputLowThresh_Data()     (CONSTVariables.POT2_InputLowThresh)
#define POT2_InputLowThresh_Ptr()      (&(CONSTVariables.POT2_InputLowThresh))
#define POT2_InputLowThresh_ELEMENTS() (1 * 1)
#define POT2_InputLow_X_Limit_Data()   (EEVariables_RAMShadow.POT2_InputLow_X_Limit)
#define POT2_InputLow_X_Limit_Ptr()    (&(EEVariables_RAMShadow.POT2_InputLow_X_Limit))
#define POT2_InputLow_X_Limit_ELEMENTS() (1 * 1)
#define POT2_InputLow_Y_Limit_Data()   (EEVariables_RAMShadow.POT2_InputLow_Y_Limit)
#define POT2_InputLow_Y_Limit_Ptr()    (&(EEVariables_RAMShadow.POT2_InputLow_Y_Limit))
#define POT2_InputLow_Y_Limit_ELEMENTS() (1 * 1)
#define POT2HighProbe_Data()           (RAMVariables.POT2HighProbe)
#define POT2HighProbe_Ptr()            (&(RAMVariables.POT2HighProbe))
#define POT2HighProbe_ELEMENTS()       (1 * 1)
#define POT2LowProbe_Data()            (RAMVariables.POT2LowProbe)
#define POT2LowProbe_Ptr()             (&(RAMVariables.POT2LowProbe))
#define POT2LowProbe_ELEMENTS()        (1 * 1)
#define POT2_ADC_Raw_Data()            (RAMVariables.POT2_ADC_Raw)
#define POT2_ADC_Raw_Ptr()             (&(RAMVariables.POT2_ADC_Raw))
#define POT2_ADC_Raw_ELEMENTS()        (1 * 1)
#define Counter_Data()                 (RAMVariables.Counter)
#define Counter_Ptr()                  (&(RAMVariables.Counter))
#define Counter_ELEMENTS()             (1 * 1)
#define GLV_hall_out_raw_override_OvrVal_Data() (RAMEditVariables.GLV_hall_out_raw_override_OvrVal)
#define GLV_hall_out_raw_override_OvrVal_Ptr() (&(RAMEditVariables.GLV_hall_out_raw_override_OvrVal))
#define GLV_hall_out_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define GLV_hall_out_raw_override_OvrSts_Data() (RAMEditVariables.GLV_hall_out_raw_override_OvrSts)
#define GLV_hall_out_raw_override_OvrSts_Ptr() (&(RAMEditVariables.GLV_hall_out_raw_override_OvrSts))
#define GLV_hall_out_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define GLV_hall_adc_Data()            (RAMVariables.GLV_hall_adc)
#define GLV_hall_adc_Ptr()             (&(RAMVariables.GLV_hall_adc))
#define GLV_hall_adc_ELEMENTS()        (1 * 1)
#define GLV_hall_amp_Data()            (RAMVariables.GLV_hall_amp)
#define GLV_hall_amp_Ptr()             (&(RAMVariables.GLV_hall_amp))
#define GLV_hall_amp_ELEMENTS()        (1 * 1)
#define Cooling_pump_PWM_D_Data()      (EEVariables_RAMShadow.Cooling_pump_PWM_D)
#define Cooling_pump_PWM_D_Ptr()       (&(EEVariables_RAMShadow.Cooling_pump_PWM_D))
#define Cooling_pump_PWM_D_ELEMENTS()  (1 * 1)
#define Pump_PWM_freq_Data()           (EEVariables_RAMShadow.Pump_PWM_freq)
#define Pump_PWM_freq_Ptr()            (&(EEVariables_RAMShadow.Pump_PWM_freq))
#define Pump_PWM_freq_ELEMENTS()       (1 * 1)
#define Flowrate_hz_corrected_override_OvrVal_Data() (RAMEditVariables.Flowrate_hz_corrected_override_OvrVal)
#define Flowrate_hz_corrected_override_OvrVal_Ptr() (&(RAMEditVariables.Flowrate_hz_corrected_override_OvrVal))
#define Flowrate_hz_corrected_override_OvrVal_ELEMENTS() (1 * 1)
#define Flowrate_hz_corrected_override_OvrSts_Data() (RAMEditVariables.Flowrate_hz_corrected_override_OvrSts)
#define Flowrate_hz_corrected_override_OvrSts_Ptr() (&(RAMEditVariables.Flowrate_hz_corrected_override_OvrSts))
#define Flowrate_hz_corrected_override_OvrSts_ELEMENTS() (1 * 1)
#define Flow_rate_gpm_override_OvrVal_Data() (RAMEditVariables.Flow_rate_gpm_override_OvrVal)
#define Flow_rate_gpm_override_OvrVal_Ptr() (&(RAMEditVariables.Flow_rate_gpm_override_OvrVal))
#define Flow_rate_gpm_override_OvrVal_ELEMENTS() (1 * 1)
#define Flow_rate_gpm_override_OvrSts_Data() (RAMEditVariables.Flow_rate_gpm_override_OvrSts)
#define Flow_rate_gpm_override_OvrSts_Ptr() (&(RAMEditVariables.Flow_rate_gpm_override_OvrSts))
#define Flow_rate_gpm_override_OvrSts_ELEMENTS() (1 * 1)
#define lowFlowRateFault_Data()        (EEVariables_RAMShadow.lowFlowRateFault)
#define lowFlowRateFault_Ptr()         (&(EEVariables_RAMShadow.lowFlowRateFault))
#define lowFlowRateFault_ELEMENTS()    (1 * 1)
#define lowFlowRate_X_Limit_Data()     (EEVariables_RAMShadow.lowFlowRate_X_Limit)
#define lowFlowRate_X_Limit_Ptr()      (&(EEVariables_RAMShadow.lowFlowRate_X_Limit))
#define lowFlowRate_X_Limit_ELEMENTS() (1 * 1)
#define lowFlowRate_Y_Limit_Data()     (EEVariables_RAMShadow.lowFlowRate_Y_Limit)
#define lowFlowRate_Y_Limit_Ptr()      (&(EEVariables_RAMShadow.lowFlowRate_Y_Limit))
#define lowFlowRate_Y_Limit_ELEMENTS() (1 * 1)
#define eradicFlowRateFault_Data()     (EEVariables_RAMShadow.eradicFlowRateFault)
#define eradicFlowRateFault_Ptr()      (&(EEVariables_RAMShadow.eradicFlowRateFault))
#define eradicFlowRateFault_ELEMENTS() (1 * 1)
#define eradicFlow_X_Limit_Data()      (EEVariables_RAMShadow.eradicFlow_X_Limit)
#define eradicFlow_X_Limit_Ptr()       (&(EEVariables_RAMShadow.eradicFlow_X_Limit))
#define eradicFlow_X_Limit_ELEMENTS()  (1 * 1)
#define eradicFlow_Y_Limit_Data()      (EEVariables_RAMShadow.eradicFlow_Y_Limit)
#define eradicFlow_Y_Limit_Ptr()       (&(EEVariables_RAMShadow.eradicFlow_Y_Limit))
#define eradicFlow_Y_Limit_ELEMENTS()  (1 * 1)
#define Flow_rate_freq_corrected_Data() (RAMVariables.Flow_rate_freq_corrected)
#define Flow_rate_freq_corrected_Ptr() (&(RAMVariables.Flow_rate_freq_corrected))
#define Flow_rate_freq_corrected_ELEMENTS() (1 * 1)
#define Flow_rate_gpm_Data()           (RAMVariables.Flow_rate_gpm)
#define Flow_rate_gpm_Ptr()            (&(RAMVariables.Flow_rate_gpm))
#define Flow_rate_gpm_ELEMENTS()       (1 * 1)
#define BMS_SOC_raw_override_OvrVal_Data() (RAMEditVariables.BMS_SOC_raw_override_OvrVal)
#define BMS_SOC_raw_override_OvrVal_Ptr() (&(RAMEditVariables.BMS_SOC_raw_override_OvrVal))
#define BMS_SOC_raw_override_OvrVal_ELEMENTS() (1 * 1)
#define BMS_SOC_raw_override_OvrSts_Data() (RAMEditVariables.BMS_SOC_raw_override_OvrSts)
#define BMS_SOC_raw_override_OvrSts_Ptr() (&(RAMEditVariables.BMS_SOC_raw_override_OvrSts))
#define BMS_SOC_raw_override_OvrSts_ELEMENTS() (1 * 1)
#define BMS_SOC_percent_Data()         (RAMVariables.BMS_SOC_percent)
#define BMS_SOC_percent_Ptr()          (&(RAMVariables.BMS_SOC_percent))
#define BMS_SOC_percent_ELEMENTS()     (1 * 1)
#define CAN1__XCP_BC_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_BC_ID)
#define CAN1__XCP_BC_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_BC_ID))
#define CAN1__XCP_BC_ID_ELEMENTS()     (1 * 1)
#define CAN1__XCP_RX_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_RX_ID)
#define CAN1__XCP_RX_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_RX_ID))
#define CAN1__XCP_RX_ID_ELEMENTS()     (1 * 1)
#define CAN1__XCP_TX_ID_Data()         (EEVariables_RAMShadow.CAN1__XCP_TX_ID)
#define CAN1__XCP_TX_ID_Ptr()          (&(EEVariables_RAMShadow.CAN1__XCP_TX_ID))
#define CAN1__XCP_TX_ID_ELEMENTS()     (1 * 1)
#define ModelName_Data()               (CONSTVariables.ModelName)
#define ModelName_Ptr()                (&(CONSTVariables.ModelName))
#define ModelName_ELEMENTS()           (1 * 11)
#define BuildNumber_Data()             (CONSTVariables.BuildNumber)
#define BuildNumber_Ptr()              (&(CONSTVariables.BuildNumber))
#define BuildNumber_ELEMENTS()         (1 * 1)
#define MatlabVersion_Data()           (CONSTVariables.MatlabVersion)
#define MatlabVersion_Ptr()            (&(CONSTVariables.MatlabVersion))
#define MatlabVersion_ELEMENTS()       (1 * 13)
#define RaptorVersion_Data()           (CONSTVariables.RaptorVersion)
#define RaptorVersion_Ptr()            (&(CONSTVariables.RaptorVersion))
#define RaptorVersion_ELEMENTS()       (1 * 20)
#define SwIdTxt_Data()                 (CONSTVariables.SwIdTxt)
#define SwIdTxt_Ptr()                  (&(CONSTVariables.SwIdTxt))
#define SwIdTxt_ELEMENTS()             (1 * 15)
#define CalIdTxt_Data()                (CONSTVariables.CalIdTxt)
#define CalIdTxt_Ptr()                 (&(CONSTVariables.CalIdTxt))
#define CalIdTxt_ELEMENTS()            (1 * 19)
#define BuildUID_Data()                (CONSTVariables.BuildUID)
#define BuildUID_Ptr()                 (&(CONSTVariables.BuildUID))
#define BuildUID_ELEMENTS()            (1 * 21)
#define IdTableRev_Data()              (CONSTVariables.IdTableRev)
#define IdTableRev_Ptr()               (&(CONSTVariables.IdTableRev))
#define IdTableRev_ELEMENTS()          (1 * 1)
#define HardwareType_Data()            (CONSTVariables.HardwareType)
#define HardwareType_Ptr()             (&(CONSTVariables.HardwareType))
#define HardwareType_ELEMENTS()        (1 * 1)
#define EcuAddr_RAM_Data()             (RAMVariables.EcuAddr_RAM)
#define EcuAddr_RAM_Ptr()              (&(RAMVariables.EcuAddr_RAM))
#define EcuAddr_RAM_ELEMENTS()         (1 * 1)
#define DateStamp_Data()               (CONSTVariables.DateStamp)
#define DateStamp_Ptr()                (&(CONSTVariables.DateStamp))
#define DateStamp_ELEMENTS()           (1 * 20)
#define INPUT29_ADCMon_HoldCount_Data() (EEVariables_RAMShadow.INPUT29_ADCMon_HoldCount)
#define INPUT29_ADCMon_HoldCount_Ptr() (&(EEVariables_RAMShadow.INPUT29_ADCMon_HoldCount))
#define INPUT29_ADCMon_HoldCount_ELEMENTS() (1 * 1)
#define CAN1__XCP_Security_Data()      (EEVariables_RAMShadow.CAN1__XCP_Security)
#define CAN1__XCP_Security_Ptr()       (&(EEVariables_RAMShadow.CAN1__XCP_Security))
#define CAN1__XCP_Security_ELEMENTS()  (1 * 1)
#define CAN1_CANTX_QueueOverrun_Data() (RAMVariables.CAN1_CANTX_QueueOverrun)
#define CAN1_CANTX_QueueOverrun_Ptr()  (&(RAMVariables.CAN1_CANTX_QueueOverrun))
#define CAN1_CANTX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN1_CANTX_QueueCount_Data()   (RAMVariables.CAN1_CANTX_QueueCount)
#define CAN1_CANTX_QueueCount_Ptr()    (&(RAMVariables.CAN1_CANTX_QueueCount))
#define CAN1_CANTX_QueueCount_ELEMENTS() (1 * 1)
#define CAN1_CANTX_QueueMax_Data()     (RAMVariables.CAN1_CANTX_QueueMax)
#define CAN1_CANTX_QueueMax_Ptr()      (&(RAMVariables.CAN1_CANTX_QueueMax))
#define CAN1_CANTX_QueueMax_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueOverrun_Data() (RAMVariables.CAN1_CANRX_QueueOverrun)
#define CAN1_CANRX_QueueOverrun_Ptr()  (&(RAMVariables.CAN1_CANRX_QueueOverrun))
#define CAN1_CANRX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueCount_Data()   (RAMVariables.CAN1_CANRX_QueueCount)
#define CAN1_CANRX_QueueCount_Ptr()    (&(RAMVariables.CAN1_CANRX_QueueCount))
#define CAN1_CANRX_QueueCount_ELEMENTS() (1 * 1)
#define CAN1_CANRX_QueueMax_Data()     (RAMVariables.CAN1_CANRX_QueueMax)
#define CAN1_CANRX_QueueMax_Ptr()      (&(RAMVariables.CAN1_CANRX_QueueMax))
#define CAN1_CANRX_QueueMax_ELEMENTS() (1 * 1)
#define CAN1_Startup_Delay_Data()      (EEVariables_RAMShadow.CAN1_Startup_Delay)
#define CAN1_Startup_Delay_Ptr()       (&(EEVariables_RAMShadow.CAN1_Startup_Delay))
#define CAN1_Startup_Delay_ELEMENTS()  (1 * 1)
#define CAN1_ErrorCheck_Interval_Data() (EEVariables_RAMShadow.CAN1_ErrorCheck_Interval)
#define CAN1_ErrorCheck_Interval_Ptr() (&(EEVariables_RAMShadow.CAN1_ErrorCheck_Interval))
#define CAN1_ErrorCheck_Interval_ELEMENTS() (1 * 1)
#define CAN1_ErrorPassive_Delay_Data() (EEVariables_RAMShadow.CAN1_ErrorPassive_Delay)
#define CAN1_ErrorPassive_Delay_Ptr()  (&(EEVariables_RAMShadow.CAN1_ErrorPassive_Delay))
#define CAN1_ErrorPassive_Delay_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueOverrun_Data() (RAMVariables.CAN2_CANTX_QueueOverrun)
#define CAN2_CANTX_QueueOverrun_Ptr()  (&(RAMVariables.CAN2_CANTX_QueueOverrun))
#define CAN2_CANTX_QueueOverrun_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueCount_Data()   (RAMVariables.CAN2_CANTX_QueueCount)
#define CAN2_CANTX_QueueCount_Ptr()    (&(RAMVariables.CAN2_CANTX_QueueCount))
#define CAN2_CANTX_QueueCount_ELEMENTS() (1 * 1)
#define CAN2_CANTX_QueueMax_Data()     (RAMVariables.CAN2_CANTX_QueueMax)
#define CAN2_CANTX_QueueMax_Ptr()      (&(RAMVariables.CAN2_CANTX_QueueMax))
#define CAN2_CANTX_QueueMax_ELEMENTS() (1 * 1)
#define CAN2_Startup_Delay_Data()      (EEVariables_RAMShadow.CAN2_Startup_Delay)
#define CAN2_Startup_Delay_Ptr()       (&(EEVariables_RAMShadow.CAN2_Startup_Delay))
#define CAN2_Startup_Delay_ELEMENTS()  (1 * 1)
#define CAN2_ErrorCheck_Interval_Data() (EEVariables_RAMShadow.CAN2_ErrorCheck_Interval)
#define CAN2_ErrorCheck_Interval_Ptr() (&(EEVariables_RAMShadow.CAN2_ErrorCheck_Interval))
#define CAN2_ErrorCheck_Interval_ELEMENTS() (1 * 1)
#define CAN2_ErrorPassive_Delay_Data() (EEVariables_RAMShadow.CAN2_ErrorPassive_Delay)
#define CAN2_ErrorPassive_Delay_Ptr()  (&(EEVariables_RAMShadow.CAN2_ErrorPassive_Delay))
#define CAN2_ErrorPassive_Delay_ELEMENTS() (1 * 1)
#define raptorFaultNonVolatileBits_Data() (EEVariables_RAMShadow.raptorFaultNonVolatileBits)
#define raptorFaultNonVolatileBits_Ptr() (&(EEVariables_RAMShadow.raptorFaultNonVolatileBits))
#define raptorFaultNonVolatileBits_ELEMENTS() (1 * 11)
#define raptorFaultCounts_X_Data()     (RAMVariables.raptorFaultCounts_X)
#define raptorFaultCounts_X_Ptr()      (&(RAMVariables.raptorFaultCounts_X))
#define raptorFaultCounts_X_ELEMENTS() (1 * 11)
#define raptorFaultCounts_Y_Data()     (RAMVariables.raptorFaultCounts_Y)
#define raptorFaultCounts_Y_Ptr()      (&(RAMVariables.raptorFaultCounts_Y))
#define raptorFaultCounts_Y_ELEMENTS() (1 * 11)
#define raptorFaultOperation_Data()    (EEVariables_RAMShadow.raptorFaultOperation)
#define raptorFaultOperation_Ptr()     (&(EEVariables_RAMShadow.raptorFaultOperation))
#define raptorFaultOperation_ELEMENTS() (1 * 11)
#define InjCDrv_EndOfStart_Data()      (EEVariables_RAMShadow.InjCDrv_EndOfStart)
#define InjCDrv_EndOfStart_Ptr()       (&(EEVariables_RAMShadow.InjCDrv_EndOfStart))
#define InjCDrv_EndOfStart_ELEMENTS()  (1 * 1)
#define EndOfStart_Data()              (EEVariables_RAMShadow.EndOfStart)
#define EndOfStart_Ptr()               (&(EEVariables_RAMShadow.EndOfStart))
#define EndOfStart_ELEMENTS()          (1 * 1)
#define EEPROM_State_Data()            (RAMVariables.EEPROM_State)
#define EEPROM_State_Ptr()             (&(RAMVariables.EEPROM_State))
#define EEPROM_State_ELEMENTS()        (1 * 1)
#define NonVolatileCRC_Data()          (EEVariables_RAMShadow.CRC)
#define NonVolatileCRC_Ptr()           (&(EEVariables_RAMShadow.CRC))

/***** CAL Locator ********************************************************/
#define CALLOC_START                   ((void*)KeySwHiTimeThr_Ptr())
#define CALLOC_LENGTH                  ( sizeof(KeySwHiTimeThr_Data()) + sizeof(KeySwLoTimeThr_Data()) + sizeof(UpperFanPoint_Data()) + sizeof(LowerFanPoint_Data()) + sizeof(Vehicle_direction_Data()) + sizeof(RPM_Data()) + sizeof(MaxTorqueMap_Data()) + sizeof(tempRateFault_Data()) + sizeof(eradicTemp_X_Limit_Data()) + sizeof(eradicTemp_Y_Limit_Data()) + sizeof(tempSenseOC_X_Limit_Data()) + sizeof(tempSenseOC_Y_Limit_Data()) + sizeof(tempSenseSC_X_Limit_Data()) + sizeof(tempSenseSC_Y_Limit_Data()) + sizeof(tempHigh_X_Limit_Data()) + sizeof(tempHigh_Y_Limit_Data()) + sizeof(Throttle_plausibility_X_Limit_Data()) + sizeof(Throttle_plausibility_Y_Limit_Data()) + sizeof(Fan_PWM_freq_Data()) + sizeof(POT1_InputHi_X_Limit_Data()) + sizeof(POT1_InputHi_Y_Limit_Data()) + sizeof(POT1_InputLow_X_Limit_Data()) + sizeof(POT1_InputLow_Y_Limit_Data()) + sizeof(POT2_InputHi_X_Limit_Data()) + sizeof(POT2_InputHi_Y_Limit_Data()) + sizeof(POT2_InputLow_X_Limit_Data()) + sizeof(POT2_InputLow_Y_Limit_Data()) + sizeof(Cooling_pump_PWM_D_Data()) + sizeof(Pump_PWM_freq_Data()) + sizeof(lowFlowRateFault_Data()) + sizeof(lowFlowRate_X_Limit_Data()) + sizeof(lowFlowRate_Y_Limit_Data()) + sizeof(eradicFlowRateFault_Data()) + sizeof(eradicFlow_X_Limit_Data()) + sizeof(eradicFlow_Y_Limit_Data()) + sizeof(CAN1__XCP_BC_ID_Data()) + sizeof(CAN1__XCP_RX_ID_Data()) + sizeof(CAN1__XCP_TX_ID_Data()) + sizeof(INPUT29_ADCMon_HoldCount_Data()) + sizeof(CAN1__XCP_Security_Data()) + sizeof(CAN1_Startup_Delay_Data()) + sizeof(CAN1_ErrorCheck_Interval_Data()) + sizeof(CAN1_ErrorPassive_Delay_Data()) + sizeof(CAN2_Startup_Delay_Data()) + sizeof(CAN2_ErrorCheck_Interval_Data()) + sizeof(CAN2_ErrorPassive_Delay_Data()) + sizeof(raptorFaultOperation_Data()) + sizeof(InjCDrv_EndOfStart_Data()) + sizeof(EndOfStart_Data()) + 0)
#endif
