/*****************************************************************************
   data.c
   Generated By:
   Raptor 2022b_1.0.14751 (6897)
   Matlab (R2022b) 9.13

   Copyright (c) 2018 New Eagle Products, Inc.
   All rights reserved.

   Code Generated at: Thu May  9 15:17:16 2024
 *****************************************************************************/

#include "raptor_types.h"
#include "data.h"
#include "string.h"                    /* TODO Reseach availabilty */
#include "Accelerator.h"
#include "Accelerator_private.h"

/* SS_DOUBLE  =  0,    / real32_T    /
   SS_SINGLE  =  1,    / real32_T  /
   SS_INT8    =  2,    / int8_T    /
   SS_UINT8   =  3,    / uint8_T   /
   SS_INT16   =  4,    / int16_T   /
   SS_UINT16  =  5,    / uint16_T  /
   SS_INT32   =  6,    / int32_T   /
   SS_UINT32  =  7,    / uint32_T  /
   SS_BOOLEAN =  8     / boolean_T */
#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

RAMVariables_T RAMVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const RAMVariables_T RAMVariables_DEFAULT = {
  55,                                  /*INIT_RAM_Variables*/
  0,                                   /* FgndTasksStopped */
  0,                                   /* KeySw_Bgnd */
  0,                                   /* KeepModuleOn */
  0.0F,                                /* AbsoluteTime */
  0U,                                  /* POT1_InputHi_Override */
  0U,                                  /* POT1_InputLow_Override */
  0U,                                  /* POT1_ADC */
  0.0F,                                /* POT1 */
  0U,                                  /* POT2_InputHi_Override */
  0U,                                  /* POT2_InputLow_Override */
  0U,                                  /* POT2_ADC */
  0.0F,                                /* POT2 */
  0,                                   /* RPM_IN */
  0,                                   /* MaxTorqueMap_Y_IN_IDX */
  0,                                   /* Torque_cmd */
  0,                                   /* Direction_cmd */
  0,                                   /* Precharge_status */
  0,                                   /* Starter_button */
  0,                                   /* Safety_loop_error_logic */
  0,                                   /* RTDS */
  0U,                                  /* Temp_adc_raw */
  0,                                   /* Temp_resistance */
  0,                                   /* Cooling_fault_any */
  0,                                   /* Charge_mode */
  0,                                   /* Starter_button_latch_q_naught */
  0,                                   /* fault_tempSenseOC */
  0,                                   /* fault_tempSenseSC */
  0,                                   /* fault_tempSenseHigh */
  0,                                   /* fault_eradic_temp */
  0,                                   /* fault_lowFlowRate */
  0,                                   /* fault_eradicFlowRate */
  0,                                   /* Temp_actual_celsius */
  0U,                                  /* Fan_PWM_D */
  0,                                   /* TSMS_logic_probe */
  0,                                   /* IMD_OkHs_probe */
  0,                                   /* IMD_GLV_probe */
  0,                                   /* RPM_val */
  0,                                   /* TP_val */
  0,                                   /* APP1 */
  0,                                   /* APP2 */
  0,                                   /* Throttle_plausibility_probe */
  0,                                   /* Drive_enable */
  0,                                   /* POT1HighProbe */
  0,                                   /* POT1LowProbe */
  0U,                                  /* POT1_ADC_Raw */
  0,                                   /* POT2HighProbe */
  0,                                   /* POT2LowProbe */
  0U,                                  /* POT2_ADC_Raw */
  0,                                   /* Counter */
  0U,                                  /* GLV_hall_adc */
  0,                                   /* GLV_hall_amp */
  0UL,                                 /* Flow_rate_freq_corrected */
  0UL,                                 /* Flow_rate_gpm */
  0U,                                  /* BMS_SOC_percent */
  11UL,                                /* EcuAddr_RAM */
  0U,                                  /* CAN1_CANTX_QueueOverrun */
  0U,                                  /* CAN1_CANTX_QueueCount */
  0U,                                  /* CAN1_CANTX_QueueMax */
  0U,                                  /* CAN1_CANRX_QueueOverrun */
  0U,                                  /* CAN1_CANRX_QueueCount */
  0U,                                  /* CAN1_CANRX_QueueMax */
  0U,                                  /* CAN2_CANTX_QueueOverrun */
  0U,                                  /* CAN2_CANTX_QueueCount */
  0U,                                  /* CAN2_CANTX_QueueMax */

  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },/* raptorFaultCounts_X */

  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, },/* raptorFaultCounts_Y */
  0U,                                  /* EEPROM_State */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initRAMVariables(RAMVariables_T* ramVariables)
{
  memcpy(ramVariables, &RAMVariables_DEFAULT, sizeof(RAMVariables_DEFAULT));
}

#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const CONSTVariables_T CONSTVariables = {
  3890.0F,                             /* POT1_ADCHiPT */
  205.0F,                              /* POT1_ADCLoPT */
  3890.0F,                             /* POT2_ADCHiPT */
  205.0F,                              /* POT2_ADCLoPT */
  3972.0F,                             /* POT1_InputHighThresh */
  123.0F,                              /* POT1_InputLowThresh */
  3972.0F,                             /* POT2_InputHighThresh */
  123.0F,                              /* POT2_InputLowThresh */

  { 65U, 99U, 99U, 101U, 108U, 101U, 114U, 97U, 116U, 111U, 114U, },/* ModelName */
  19UL,                                /* BuildNumber */

  { 40U, 82U, 50U, 48U, 50U, 50U, 98U, 41U, 32U, 57U, 46U, 49U, 51U, },/* MatlabVersion */

  { 50U, 48U, 50U, 50U, 98U, 95U, 49U, 46U, 48U, 46U, 49U, 52U, 55U, 53U, 49U,
    95U, 54U, 56U, 57U, 55U, },        /* RaptorVersion */

  { 65U, 99U, 99U, 101U, 108U, 101U, 114U, 97U, 116U, 111U, 114U, 95U, 48U, 49U,
    57U, },                            /* SwIdTxt */

  { 65U, 99U, 99U, 101U, 108U, 101U, 114U, 97U, 116U, 111U, 114U, 95U, 48U, 49U,
    57U, 95U, 48U, 48U, 48U, },        /* CalIdTxt */

  { 120U, 122U, 88U, 120U, 83U, 56U, 85U, 74U, 118U, 85U, 54U, 116U, 106U, 117U,
    51U, 86U, 122U, 71U, 65U, 68U, 48U, },/* BuildUID */
  3,                                   /* IdTableRev */
  2954298118UL,                        /* HardwareType */

  { 48U, 57U, 45U, 77U, 97U, 121U, 45U, 50U, 48U, 50U, 52U, 32U, 49U, 53U, 58U,
    49U, 55U, 58U, 49U, 54U, },        /* DateStamp */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initCONSTVariables(const CONSTVariables_T* cv)
{

#ifdef UNUSED

  UNUSED(cv);

#endif

}

/* Total EEPROM Structure Size: 449U Bytes */
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const EEVariables_T EEVariables_DEFAULT = {
  0,                                  /* Write Count: Identifies active Copy 	*/
  1255569992U,                         /* EE_UniqID 	*/

  { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, },/* raptorFaultNonVolatileBits */
  0.2F,                                /* KeySwHiTimeThr */
  0.2F,                                /* KeySwLoTimeThr */
  150.0F,                              /* UpperFanPoint */
  65.0F,                               /* LowerFanPoint */
  0.0F,                                /* Vehicle_direction */

  { 1.527788213F, 158.0133744F, 323.7157813F, 498.6851003F, 719.5381571F,
    894.5575676F, 1069.476795F, 1235.229293F, 1400.981792F, 1585.167931F,
    1806.271445F, 1981.340947F, 2156.360358F, 2331.479951F, 2497.382723F,
    2672.502317F, 2903.023017F, 3078.192702F, 3253.362386F, 3419.365342F,
    3594.685301F, 3825.306184F, 4055.826884F, 4286.54795F, 4461.867909F,
    4627.971047F, 4803.291006F, 4969.394144F, 5200.165302F, 5375.535352F,
    5541.63849F, 5772.359556F, 5947.779698F, },/* RPM */

  { 72.93410474F, 73.78666066F, 74.63821474F, 75.27137025F, 76.76910361F,
    77.18486237F, 78.03541463F, 78.66957197F, 79.30372931F, 79.93588299F,
    80.3466326F, 80.54499462F, 80.96075337F, 80.94171864F, 80.92368573F,
    80.90465099F, 80.44481178F, 80.20838029F, 79.97194881F, 79.5191224F,
    78.63050066F, 77.73586796F, 77.27602875F, 75.94660255F, 75.05798081F,
    74.17036091F, 73.28173917F, 72.39411927F, 70.84729632F, 69.74127783F,
    68.85365793F, 67.52423172F, 66.20081649F, },/* MaxTorqueMap */
  10.0F,                               /* tempRateFault */
  25UL,                                /* eradicTemp_X_Limit */
  50UL,                                /* eradicTemp_Y_Limit */
  25UL,                                /* tempSenseOC_X_Limit */
  50UL,                                /* tempSenseOC_Y_Limit */
  25UL,                                /* tempSenseSC_X_Limit */
  50UL,                                /* tempSenseSC_Y_Limit */
  25UL,                                /* tempHigh_X_Limit */
  50UL,                                /* tempHigh_Y_Limit */
  25UL,                                /* Throttle_plausibility_X_Limit */
  50UL,                                /* Throttle_plausibility_Y_Limit */
  24000UL,                             /* Fan_PWM_freq */
  25UL,                                /* POT1_InputHi_X_Limit */
  50UL,                                /* POT1_InputHi_Y_Limit */
  25UL,                                /* POT1_InputLow_X_Limit */
  50UL,                                /* POT1_InputLow_Y_Limit */
  25UL,                                /* POT2_InputHi_X_Limit */
  50UL,                                /* POT2_InputHi_Y_Limit */
  25UL,                                /* POT2_InputLow_X_Limit */
  50UL,                                /* POT2_InputLow_Y_Limit */
  0.4F,                                /* Cooling_pump_PWM_D */
  24000UL,                             /* Pump_PWM_freq */
  1.0F,                                /* lowFlowRateFault */
  25UL,                                /* lowFlowRate_X_Limit */
  50UL,                                /* lowFlowRate_Y_Limit */
  10.0F,                               /* eradicFlowRateFault */
  25UL,                                /* eradicFlow_X_Limit */
  50UL,                                /* eradicFlow_Y_Limit */
  256UL,                               /* CAN1__XCP_BC_ID */
  512UL,                               /* CAN1__XCP_RX_ID */
  768UL,                               /* CAN1__XCP_TX_ID */
  3U,                                  /* INPUT29_ADCMon_HoldCount */
  20037U,                              /* CAN1__XCP_Security */
  500U,                                /* CAN1_Startup_Delay */
  20U,                                 /* CAN1_ErrorCheck_Interval */
  20U,                                 /* CAN1_ErrorPassive_Delay */
  500U,                                /* CAN2_Startup_Delay */
  20U,                                 /* CAN2_ErrorCheck_Interval */
  20U,                                 /* CAN2_ErrorPassive_Delay */

  { FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING, FLTOP_NOTHING,
    FLTOP_NOTHING, },                  /* raptorFaultOperation */
  1U,                                  /* InjCDrv_EndOfStart */
  1U,                                  /* EndOfStart */
  0,                                   /* CRC Initial Value */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

EEVariables_T EEVariables_RAMShadow ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

uint32_T g_EE_LoadedCopy = 0;

#define FEE_NUM_PAGES                  18

uint16_T read_eeprom(void);

#define EE_PAGE_SIZE                   120
#define FEE_MAX_NUM_PAGES              18
#define FEE_SIZE_CALC()                (((uint32_T)&FEEVariables_RAMShadow.CRC - (uint32_T)&FEEVariables_RAMShadow) + 2)
#define EE_SIZE_CALC()                 (((uint32_T)&EEVariables_RAMShadow.CRC - (uint32_T)&EEVariables_RAMShadow) + 2)
#define RETRY_MAX                      1000

bool g_feeWrite_Started = 0;

/* MANAGE EE PROM MEMORY */
void App_EE_Defaults(void)
{
  memcpy(&EEVariables_RAMShadow, &EEVariables_DEFAULT, sizeof(EEVariables_T));
  EEPROM_State_Data() = EE_LOADED_DEFAULTS;
}

void App_EE_Init(void);
void App_EE_Init(void)
{
  uint8_T firstStart= 0;
  uint32_T ee_size = EE_SIZE_CALC();
  if ((Reset_xHistBuf[0] == SWRESET_CBPROG_E) || ((Reset_xHistBuf[0] ==
        SWRESET_POWERON_SIMU_E) && (Reset_xHistBuf[1] == SWRESET_CBPROG_E))) {
    /* SWRESET_CBPROG_E */
    /* SWRESET_POWERON_SIMU_E, SWRESET_CBPROG_E */
    firstStart = (Reset_Env.xGrp == 0x06);
  } else if ((Reset_xHistBuf[0] == RESET_SWRESET_MOCRAM_REPEXOK) &&
             (Reset_xHistBuf[1] == SWRESET_POWERON_SIMU_E) && (Reset_xHistBuf[2]
              == SWRESET_CBPROG_E)) {
    /*RESET_SWRESET_MOCRAM_REPEXOK, SWRESET_POWERON_SIMU_E, SWRESET_CBPROG_E */
    firstStart = (Reset_Env.xGrp == 0x07);
  }

  /* Fixed NV Read */
  if (firstStart) {
    /* Load defaults after programming - new values may have been merged into EEVariables_DEFAULT */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_AFTER_PROGRAMMING;
  } else if (read_eeprom() != SWS_EEP_SUCCEEDED) {
    /* Revert to defaults - error reading stored data */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_ERROR_READING;
  } else if (EEVariables_RAMShadow.EE_UniqID != EEVariables_DEFAULT.EE_UniqID) {
    /* Revert to defaults - the data stored previously doesn't match the format for the current application */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_INCORRECT_EEID;
  } else if (!is_crc_valid((void*)&EEVariables_RAMShadow, ee_size-2,
              EEVariables_RAMShadow.CRC)) {
    /* Revert to defaults - stored data is corrupted */
    App_EE_Defaults();
    EEPROM_State_Data() = EE_LOADED_DEFAULTS_INCORRECT_CRC;
  } else {
    /* Normal case startup, reloaded values */
    EEPROM_State_Data() = EE_LOADED_SAVED_VALUES;
                                      /* Normal case startup, reloaded values */
  }
}

void App_EE_Store(void)
{
  if (EEPROM_State_Data() != EE_STORE_IN_PROGESS) {
    EEPROM_State_Data() = EE_STORE_IN_PROGESS;
    App_EE_WriteAsync(1);
  }
}

/* Extra Funcitons Definitions for EEPROM */
uint16_T read_eeprom(void)
{
  swsEEP_ret result;
  uint16_T eeReadIdx = 20;
  uint8_T readBuf[120];
  uint8_T retryCnt = 0;
  uint8_T* wrPtr = (uint8_T*)&EEVariables_RAMShadow;
  uint32_T ee_size = EE_SIZE_CALC();
  uint16_T total_EE_PgCnt = (ee_size / EE_PAGE_SIZE) + ((ee_size % EE_PAGE_SIZE)
    > 0);
  uint16_T lastPageIdx = total_EE_PgCnt + 20;
  uint16_T lastFullpageIndx = 0;
  eeReadIdx = 20;
  lastPageIdx = total_EE_PgCnt + eeReadIdx;
  if ((EE_SIZE_CALC() % EE_PAGE_SIZE) == 0) {
    lastFullpageIndx = lastPageIdx;
  } else {
    lastFullpageIndx = lastPageIdx - 1;
  }

  /* READ Full EEPROM */
  for (; eeReadIdx < lastPageIdx; eeReadIdx++) {
    retryCnt = 0;
    for (retryCnt = 0; retryCnt < 25; retryCnt++) {
      result = swsEEP_Read_Directly((void*)&readBuf, eeReadIdx);
      if (result == SWS_EEP_SUCCEEDED) {
        break;
      }
    }

    if (result == SWS_EEP_SUCCEEDED) {
      /* copy into EEVariables_RAMShadow	*/
      if (eeReadIdx < lastFullpageIndx) {
        memcpy(wrPtr, &readBuf, EE_PAGE_SIZE);
        wrPtr += EE_PAGE_SIZE;
      } else {
        uint16_T eeReadSize = (EE_SIZE_CALC() % EE_PAGE_SIZE);
        if (eeReadSize == 0) {
          eeReadSize = EE_PAGE_SIZE;
        }

        memcpy(wrPtr, &readBuf, eeReadSize);
      }
    } else {
      break;
    }
  }

  return result;
}

void App_EE_WriteAsync(uint8_T startWrite)
{
  static uint32_T ee_size = 0;
  static uint16_T total_EE_PgCnt = 0;
  static bool eeWrite_Started = 0;
  static uint16_T eeWrite_RetryCnt = 0;
  static uint8_T* eeWrite_Ptr;
  static uint16_T eeWrite_Idx = 20;
  static uint16_T runningCRC = 0xFFFF;
  static uint32_T ee_WriteLen = 0;
  static uint16_T lastPageIdx = 0;
  static uint8_T writeBuffer[EE_PAGE_SIZE] = { 0 };

  swsEEP_ret result;

  //only execute if we are starting a write or already have one in progress
  if (!startWrite && !eeWrite_Started) {
    return;
  }

  if (!eeWrite_Started) {
    eeWrite_RetryCnt = 0;
    eeWrite_Ptr = (void*)&EEVariables_RAMShadow;
    EEPROM_State_Data() = EE_STORE_IN_PROGESS;
    ee_size = EE_SIZE_CALC();
    total_EE_PgCnt = (ee_size / EE_PAGE_SIZE) + ((ee_size % EE_PAGE_SIZE) > 0);
    eeWrite_Started = 1;
    eeWrite_Idx = 20;
    ee_WriteLen = EE_PAGE_SIZE;
    lastPageIdx = total_EE_PgCnt + eeWrite_Idx - 1;
    runningCRC = 0xFFFF;
    if (total_EE_PgCnt == 1) {
      SuspInt();                     //suspend interrupts while we calculate CRC

      //and copy to write buffer so data is not modified elsewhere

      //EE is a single page
      ee_WriteLen = ee_size;
      runningCRC = crc16_spd((void*)&EEVariables_RAMShadow, ee_WriteLen-2,
        runningCRC);
      EEVariables_RAMShadow.CRC = runningCRC;
      memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
      ResInt();
    } else {
      memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
      runningCRC = crc16_spd((void*)&writeBuffer, ee_WriteLen, runningCRC);
    }

    // Write the first set of pages to the queue
    result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
  } else {
    // Check status of previous page writes
    result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
    if (result == SWS_EEP_SUCCEEDED) {
      //Success
      eeWrite_RetryCnt = 0;
      eeWrite_Idx++;
      eeWrite_Ptr += EE_PAGE_SIZE;
      if (eeWrite_Idx == lastPageIdx ) {
        //last page, update crc
        SuspInt();                   //suspend interrupts while we calculate CRC

        //and copy to write buffer so data is not modified elsewhere
        ee_WriteLen = ee_size % EE_PAGE_SIZE;
        if (ee_WriteLen == 0) {
          ee_WriteLen = EE_PAGE_SIZE;
        }

        runningCRC = crc16_spd((void*)eeWrite_Ptr, ee_WriteLen-2, runningCRC);
        EEVariables_RAMShadow.CRC = runningCRC;
        memcpy((void*)&writeBuffer, (void*)eeWrite_Ptr, ee_WriteLen);
        ResInt();
      } else if (eeWrite_Idx < lastPageIdx) {
        memcpy((void*)&writeBuffer, eeWrite_Ptr, ee_WriteLen);
        runningCRC = crc16_spd((void*)&writeBuffer, ee_WriteLen, runningCRC);
      }

      /* Queue up the write operatation */
      if (eeWrite_Idx <= lastPageIdx) {
        // write new page
        result = swsEEP_Write_Directly((void*)&writeBuffer, eeWrite_Idx);
      } else {
        //finished
        eeWrite_Started = 0;
        EEPROM_State_Data() = EE_STORE_SUCCESS;
      }
    } else if (eeWrite_RetryCnt < RETRY_MAX) {
      //we will check next time
      eeWrite_RetryCnt++;
    } else {
      //Abort Operation
      EEPROM_State_Data() = EE_STORE_FAILED;
      eeWrite_Started = 0;
    }
  }
}

#define START_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"

RAMEditVariables_T RAMEditVariables ;

#define STOP_SECTION_volatile_SlowRam_oem_32bit
#include "swsh_rb2oem.h"
#define START_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

const RAMEditVariables_T RAMEditVariables_DEFAULT = {
  55,                                  /*INIT_RAM_EditVariables*/
  0.0F,                                /* APP_override_OvrVal */
  0U,                                  /* APP_override_OvrSts */
  0.0F,                                /* APP_default_err_override_OvrVal */
  0U,                                  /* APP_default_err_override_OvrSts */
  0.0F,                                /* Direction_cmd_override_OvrVal */
  0U,                                  /* Direction_cmd_override_OvrSts */
  0U,                                  /* POT1_InputHi_Override_OvrVal */
  0U,                                  /* POT1_InputHi_Override_OvrSts */
  0U,                                  /* POT1_InputLow_Override_OvrVal */
  0U,                                  /* POT1_InputLow_Override_OvrSts */
  0U,                                  /* POT1_ADC_OvrVal */
  0U,                                  /* POT1_ADC_OvrSts */
  0.0F,                                /* POT1_OvrVal */
  0U,                                  /* POT1_OvrSts */
  0.0F,                                /* APP1_override_OvrVal */
  0U,                                  /* APP1_override_OvrSts */
  0U,                                  /* POT2_InputHi_Override_OvrVal */
  0U,                                  /* POT2_InputHi_Override_OvrSts */
  0U,                                  /* POT2_InputLow_Override_OvrVal */
  0U,                                  /* POT2_InputLow_Override_OvrSts */
  0U,                                  /* POT2_ADC_OvrVal */
  0U,                                  /* POT2_ADC_OvrSts */
  0.0F,                                /* POT2_OvrVal */
  0U,                                  /* POT2_OvrSts */
  0.0F,                                /* APP2_override_OvrVal */
  0U,                                  /* APP2_override_OvrSts */
  0U,                                  /* Starter_button_raw_override_OvrVal */
  0U,                                  /* Starter_button_raw_override_OvrSts */
  0U,                                /* Safety_loop_error_raw_override_OvrVal */
  0U,                                /* Safety_loop_error_raw_override_OvrSts */
  0U,                                  /* Starter_button_override_OvrVal */
  0U,                                  /* Starter_button_override_OvrSts */
  0U,                                  /* Precharge_raw_override_OvrVal */
  0U,                                  /* Precharge_raw_override_OvrSts */
  0U,                                  /* Charge_mode_raw_override_OvrVal */
  0U,                                  /* Charge_mode_raw_override_OvrSts */
  0U,                                  /* Cooling_fault_any_override_OvrVal */
  0U,                                  /* Cooling_fault_any_override_OvrSts */
  0U,                                  /* Drive_enable_override_OvrVal */
  0U,                                  /* Drive_enable_override_OvrSts */
  0U,                                  /* Inverter_enb_override_OvrVal */
  0U,                                  /* Inverter_enb_override_OvrSts */
  0.0F,                                /* RPM_override_OvrVal */
  0U,                                  /* RPM_override_OvrSts */
  0.0F,                                /* Torque_map_val_override_OvrVal */
  0U,                                  /* Torque_map_val_override_OvrSts */
  0.0F,                                /* Torque_cmd_override_OvrVal */
  0U,                                  /* Torque_cmd_override_OvrSts */
  0U,                                  /* RTDS_override_OvrVal */
  0U,                                  /* RTDS_override_OvrSts */
  0U,                                  /* TSMS_ADC_override_OvrVal */
  0U,                                  /* TSMS_ADC_override_OvrSts */
  0U,                                  /* IMD_GLV_override_OvrVal */
  0U,                                  /* IMD_GLV_override_OvrSts */
  0U,                                  /* IMD_OkHs_override_OvrVal */
  0U,                                  /* IMD_OkHs_override_OvrSts */
  0U,                                  /* Temp_adc_raw_override_OvrVal */
  0U,                                  /* Temp_adc_raw_override_OvrSts */
  0.0F,                                /* Temp_resistance_override_OvrVal */
  0U,                                  /* Temp_resistance_override_OvrSts */
  0.0F,                                /* Temp_actual_celsius_override_OvrVal */
  0U,                                  /* Temp_actual_celsius_override_OvrSts */
  0U,                                  /* Fan_PWM_D_override_OvrVal */
  0U,                                  /* Fan_PWM_D_override_OvrSts */
  0U,                                  /* GLV_hall_out_raw_override_OvrVal */
  0U,                                  /* GLV_hall_out_raw_override_OvrSts */
  0UL,                               /* Flowrate_hz_corrected_override_OvrVal */
  0U,                                /* Flowrate_hz_corrected_override_OvrSts */
  0UL,                                 /* Flow_rate_gpm_override_OvrVal */
  0U,                                  /* Flow_rate_gpm_override_OvrSts */
  0U,                                  /* BMS_SOC_raw_override_OvrVal */
  0U,                                  /* BMS_SOC_raw_override_OvrSts */
};

#define STOP_SECTION_Const_oem_32bit
#include "swsh_rb2oem.h"

void initRAMEditVariables(void)
{
  memcpy(&RAMEditVariables, &RAMEditVariables_DEFAULT, sizeof
         (RAMEditVariables_DEFAULT));
}
